Fix for #9589 Incorrect Export of Search Results with Double Quotation Marks in DSpace 7.
DSpace/DSpace pull request #10103
Opened 2024-12-11 13:30 UTC by im-shubham-vish

## References
* Fixes #9589

## Description
When exporting search results in DSpace 7 that include double quotation marks in the search query, the export does not reflect the original search query with double quotation marks. Instead, it exports the results of the search query without the double quotation marks.

## Instructions for Reviewers
Export the search results after performing a search in DSpace using a query that includes double quotation marks, for example: "search term". The export of search result bringing extra results in it which are not there in the result of original double quoted search query results.

## List of changes in this PR:
* Added minor change inside the parse method under DSpaceRunnable class to set StripLeadingAndTrailingQuotes as false in default parser builder.

## Guidance for how to test or review this PR 
1. Login with any user
1. Perform a search in DSpace using a query that includes double quotation marks, for example: "dengue vaccination".
2. Export the search results by clicking on Export search results as CSV.
3. Observe the export does not reflect the original search query result and instead exports the results without the double quotation marks also.

2025-05-14 11:49 UTC, kanasznagyzoltan commented
**Testing results:**

1. Search results **without double quotation** marks:

![image](https://github.com/user-attachments/assets/0218ff10-c7c5-4a26-84e5-2a350abcc1c1)

- Exported search:

![image](https://github.com/user-attachments/assets/b8d9ede9-9493-44cb-8fa7-d7ca5dbad456)

2.  Search results **with double quotation** marks:

![image](https://github.com/user-attachments/assets/92debd9e-70c0-4967-a9f9-366985305df1)

- Exported search:

![image](https://github.com/user-attachments/assets/6b680f26-4439-4122-b295-5b563665a8a9)

**It seems to be working correctly. DSpace only exports the items that are in the result of the specific search query.**

2025-06-21 08:40 UTC, PitbaranK commented
@tdonohue,
Kindly help us by reviewing and merging the changes in this pull request.
If you have any feedback or suggestions, please feel free to share — we’re happy to connect and make any necessary adjustments.

2025-07-31 15:05 UTC, kshepherd commented
This change makes sense, but it is very low level and could potentially have unexpected side effects with argument parsing of other scripts, arguments commonly used with DSpaceRunnables.

Could we think about adding tests for arguments with quotes in other runnables?

If we want to be extra safe, we could instead override `MetadataExportSearch#parse` since that is extending `DSpaceRunnable`.

In 2009, this was the only commons-cli parsing behaviour and was reported as a bug: https://issues.apache.org/jira/browse/CLI-185

But there is reasonable discussion there about whether most environments actually pass outer quotes to the applications when sending args, what the applications expect, and what the best default is.

The `DefaultParser` doc mentions this "historical behaviour" to explain its default value and behaviour:  https://commons.apache.org/proper/commons-cli/apidocs/org/apache/commons/cli/DefaultParser.Builder.html#setStripLeadingAndTrailingQuotes(java.lang.Boolean)

2025-07-31 15:17 UTC, tdonohue requested changes
@im-shubham-vish : we discussed this PR as a team in today's Developers Meeting.  Several of the Committers in attendance agreed that adding this code to `DSpaceRunnable` is potentially dangerous, as it would then be used by **every script** that is runnable from the DSpace User Interface (on the Processes page).   That could have unforeseen side effects on other scripts.

As @kshepherd notes in his comment above, the better approach would be to make this change **only to the [`MetadataExportSearch`](https://github.com/DSpace/DSpace/blob/main/dspace-api/src/main/java/org/dspace/app/bulkedit/MetadataExportSearch.java)** script which is being used to export the search results.  That'd ensure this change only impacts that single script instead of all scripts.

To make that change you'd likely need to add an `@Override` version of this `parse()` method to the existing `MetadataExportSearch` script and move the code to that location.

We also should add an automated test to the existing [`MetadataExportSearchIT`](https://github.com/DSpace/DSpace/blob/main/dspace-api/src/test/java/org/dspace/app/bulkedit/MetadataExportSearchIT.java) which proves that this fixes the double quotes issue.

Once this code is moved and an integration test is added, then I think this would be a great contribution to fix this bug.  Thanks!

2025-08-12 07:42 UTC, closed without merging

2025-08-12 11:54 UTC, im-shubham-vish commented
@tdonohue For your reference we have incorporated the reviewed feedback in another PR #11150, due to bot closed this PR#10103 with unmerged commits. Please let us know in case you have any feedback over here.