DS-2656: Tidy up whitespaces, tabs, etc in input-forms.xml
DSpace/DSpace pull request #1158
Opened 2015-11-11 20:17 UTC by alanorth

Generated with the following command:

```
$ tidy -xml -iq -m -w 0  dspace/config/input-forms.xml
```

Results in no functional changes, only aesthetic.

2015-11-13 10:12 UTC, helix84 commented
I don't like the blank lines removed, that makes readability worse.

2015-11-13 11:50 UTC, alanorth commented
To be fair, it's not meant to be readable to you—it's machine-readable XML. ;)

In our institute I run tidy after every modification I make to our subject terms, before committing to the repo.

2015-11-13 12:29 UTC, helix84 commented
The machine doesn't care about this whitespace change in the slightest. The humans who edit it probably do. There's merit in making it the file readable, which is why you are making this PR. I don't object to formatting it, just to one specific formatting change.

2015-11-13 12:37 UTC, alanorth commented
I guess it depends who is editing it. I'm a systems admin, and I edit it in vim in a terminal. It's actually *because* of our librarians editing it and introducing all manner of white space errors that I started formatting it in the first place!

2015-11-13 13:27 UTC, mwoodiupui commented
I must agree that I'd prefer not to lose the whitespace.

2017-02-21 21:16 UTC, tdonohue requested changes
Agreed with others that the veritical whitespace would be nice to keep. I'm OK with cleaning up tabbing, trailing spaces though, if this PR was updated.

2017-02-22 12:07 UTC, alanorth commented
It's ok, @tdonohue. I will close this pull request and just continue to format / audit our file for correctness with `tidy` locally. My main gripe was that our once-yearly rebase on top of new DSpace release branches cause tons of merge conflicts due to whitespace.

2017-02-22 12:07 UTC, closed without merging