DS-3377 Solr query may be longer than allowed by the Web Container
DSpace/DSpace pull request #1563
Opened 2016-11-07 17:18 UTC by nicolasschwab

Now only the UUID of the comm/coll the user has explicit ADMIN authorization
on are added to the "location" parameter

2017-02-03 21:36 UTC, tdonohue requested changes
Needs rebasing, as this has merge conflicts

2017-02-20 17:56 UTC, pnbecker commented
Beside the necessary rebase, I also don't agree with the idea of this PR. In DSpace we use the concept of groups, subgroups and inheritance of permissions from groups to subgroups to EPersons.

2017-06-21 19:24 UTC, terrywbrady requested changes
See question about inserting OR between a list of communities and a list of collections.

2017-06-21 19:24 UTC, terrywbrady commented on dspace-api/src/main/java/org/dspace/discovery/SolrServiceImpl.java
> +            	locationQuery.append(this.getLocationOfEachResourcePolicy(collectionsPolicies, context));
If both communitiesPolicies and collectionsPolicies exist, will the " OR " be inserted between the 2 lists?

2017-06-21 19:52 UTC, terrywbrady commented on dspace-api/src/main/java/org/dspace/discovery/SolrServiceImpl.java
> +            	locationQuery.append(this.getLocationOfEachResourcePolicy(collectionsPolicies, context));
I validated the issue that I reported above.  When a user has ADMIN rights to both collections and communities, the location search is corrupted.

> )+OR+location:(+mfc564c62-b178-4d8b-8789-995e3e7e5377+OR+m40249564-ea3a-4bdc-86fd-21cf6b554187ld65b663c-647c-4a4f-9737-671af7f0c8ab+)

2017-06-21 19:58 UTC, terrywbrady commented on dspace-api/src/main/java/org/dspace/discovery/SolrServiceImpl.java
> +            	locationQuery.append(this.getLocationOfEachResourcePolicy(collectionsPolicies, context));
Aside from the issue reported above, when I test with this patch, the same number of objects are returned when only the root location is included in the search, so I think this PR should be merged once the bug is fixed.

2017-06-21 20:12 UTC, terrywbrady commented on dspace-api/src/main/java/org/dspace/discovery/SolrServiceImpl.java
> +            	locationQuery.append(this.getLocationOfEachResourcePolicy(collectionsPolicies, context));
The following commit should resolve the bug: https://github.com/Georgetown-University-Libraries/DSpace/commit/4454550911781a293fdd383d37b9b81602955c3e

2018-05-03 15:33 UTC, tdonohue commented
Note: there is an alternative PR which simply changes all Solr requests to HTTP POST, see #2045   Unless anyone feels differently, we may be able to close this PR in favor of that new one.

2018-08-22 20:45 UTC, tdonohue commented
Closing, as this was fixed in #2045

2018-08-22 20:45 UTC, closed without merging