DS-3385 add OAI excludeSet filter
DSpace/DSpace pull request #1576
Opened 2016-11-23 13:12 UTC by helix84

not tested yet

2017-02-01 16:11 UTC, rivaldi8 requested changes
String comparisons should be fixed. Apart from this, it works perfectly. I've tested excluding a single collection, multiple collections and a mix of collections and communities. The tests have been done in DSpace 5.6.

2017-02-01 16:13 UTC, rivaldi8 commented on dspace-oai/src/main/java/org/dspace/xoai/filter/DSpaceExcludeSetFilter.java
> +            if (excludeSets.get(i).substring(0, 4) == "col_") {
This should be:
```
    if (excludeSets.get(i).substring(0, 4).equals("col_")) {
```

2017-02-01 16:13 UTC, rivaldi8 commented on dspace-oai/src/main/java/org/dspace/xoai/filter/DSpaceExcludeSetFilter.java
> +            } else if (excludeSets.get(i).substring(0, 4) == "com_") {
This should also use `equals`.

2017-02-01 16:21 UTC, rivaldi8 commented
The configuration should be like this instead:
- In the Filters section of xoai.xml:
```
        <Filter id="excludeSetFilter">
            <Definition>
                <Custom ref="excludeSetFilterCondition"/>
            </Definition>
        </Filter>

        <CustomCondition id="excludeSetFilterCondition">
            <Class>org.dspace.xoai.filter.DSpaceExcludeSetFilter</Class>
            <Configuration>
                <string name="excludeSet">col_123456789_371</string>
            </Configuration>
        </CustomCondition>
```
- In the Context definition (`ref` instead of `refid`):
```
 <Context baseurl="request">
   [...]
   <Filter ref="excludeSetFilter" />
 </Context>
```

2017-02-02 08:04 UTC, rivaldi8 approved these changes
That's correct now.

2017-02-23 18:34 UTC, tdonohue approved these changes
👍 This code looks reasonable to me. However, if merged, I'd like to see some documentation/examples added on how it can be used.

2017-02-27 12:33 UTC, rivaldi8 commented
Could someone comfirm that this is working?

After another round of tests in our way to upgrading to DSpace 5.6, I found that the filter is no longer working properly.

Listing all items works (`?verb=ListRecords&metadataPrefix=oai_dc`). I get all records minus the ones in the excluded collection.  parameter).

However, adding a set (`?verb=ListRecords&metadataPrefix=oai_dc&set=com_10459.1_2`) yields no matches.

In the Solr logs I see this query:
```
((NOT (item.collections:col_10459.1_371))) AND ((item.communities:com_10459.1_2))
```

Each condition seems to get two extra pair of parenthesis. If remove them like below, I get the correct list of records (tested from Solr admin):
```
NOT (item.collections:col_10459.1_371) AND ((item.communities:com_10459.1_2))
```

Alternatively, adding `*:*` at the beginning seems to make it work too:
```
((*:* NOT (item.collections:col_10459.1_371))) AND ((item.communities:com_10459.1_2))
```

I'm totally lost as to why this worked and now doesn't, so any hint will be highly appreciated.

2017-03-03 11:26 UTC, rivaldi8 commented
I've found [this issue](https://jira.duraspace.org/browse/DS-2820) about a similar problem. I still don't understand why it worked in the first tests.

2017-03-06 19:20 UTC, antoine-atmire commented
> I'm totally lost as to why this worked and now doesn't, so any hint will be highly appreciated.
Solr doesn't support expressions where everything is a `NOT`. Except when that expression is the top expression... So every time a part within nested parentheses is like that, there aren't any matches.

When you add `*:*` in front of it, the query behaves as expected again. It works now because the expression isn't all-negative anymore. This is a fine solution, it's easy to implement and the logic is sound.

2018-09-07 02:56 UTC, ppmdo commented
I've worked this out with the fixed suggested by @antoine-atmire. Although it seems this PR has been abandoned for a while, so is it possible to push the fix to this PR or should I open another?

2026-03-23 16:32 UTC, tdonohue commented
Closing, as this PR seems abandoned & sounds like it needs updates [based on the discussion above](https://github.com/DSpace/DSpace/pull/1576#issuecomment-419305799).  If anyone wants to create a fresh PR, please feel free.

2026-03-23 16:32 UTC, closed without merging