[DS-3406] add collection and subcommunity sorting by name comparator to Community getters
DSpace/DSpace pull request #1638
Opened 2017-02-02 08:53 UTC by kshepherd

This PR resolves the collection/sub-community sorting issue described in [DS-3406](https://jira.duraspace.org/browse/DS-3406) for XMLUI and JSPUI, forcing a sort by getName() for collections, sub-communities and parent communities of a community.

It might be considered too expensive / adding unnecessary complexity to these otherwise simple getters? Another way could be to wire in some @OrderBy SQL sort for the entities in question? (but that makes an assumption on field usage unlike the comparators which use getName() to get title from wherever/whatever the collection metadata is)

To test, rebuild discovery indexes after rebuild and restart.

2017-02-02 10:26 UTC, kshepherd commented
unit tests fail at getAllParents, and continue from there in CommunityTests, even after allowing for null results from getName(), so this approach might not work after all. needs a rethink.

2017-02-02 11:17 UTC, tomdesair commented
As suggested in Jira, I would change the comparator implementation to a general DSpaceObject Name comparator: https://github.com/YanaDP/DSpace/commit/177b5e95489931eadbf600c5c0391fefb33b2344#diff-f47e1ad6a54102eb6a012bbffdd87931

2017-02-23 18:30 UTC, tdonohue requested changes
@kshepherd : this is currently failing tests. Per your comment about "needs a rethink", are you wanting to keep working on this PR, or shall we close this and look for a new volunteer?

2017-03-08 15:24 UTC, tdonohue commented
Closing as this PR seems to be inactive/abandoned. We can reopen if needed, but from the comments above, this sounds like it needs rework (and I plan to revert the associated ticket back to "needs volunteer")

2017-03-08 15:24 UTC, closed without merging