Add endpoints for the Site object
DSpace/DSpace pull request #1680
Opened 2017-03-20 22:05 UTC by terrywbrady

Adding support to obtain the Site object from the repository since this will likely be needed to generate the collection hierarchy.

2017-03-22 20:50 UTC, terrywbrady commented
Note that AIP import/export functions require a user to have access to the site object. If we intend to pass those operations through REST, we will need to expose the site object.

2017-03-23 16:41 UTC, terrywbrady commented
Updated base to point to master

2017-03-30 16:03 UTC, mwoodiupui commented on dspace-spring-rest/src/main/java/org/dspace/app/rest/repository/SiteRestRepository.java
> +		System.out.println("Repository initialized by Spring");
Shouldn't this go to the log, at DEBUG level?

2017-03-30 20:44 UTC, abollini requested changes

2017-03-30 20:46 UTC, abollini commented on dspace-spring-rest/src/main/java/org/dspace/app/rest/repository/SiteRestRepository.java
> +		System.out.println("Repository initialized by Spring");
this is a sysout that I have introduced in early stage of the development and we have copied and paste over all the repository now. We should just remove this statement.

2017-03-30 21:33 UTC, terrywbrady commented
@abollini , I made the changes requested and have retested this change

2017-04-02 13:07 UTC, abollini approved these changes

2017-04-02 13:07 UTC, merged