DS-3406: Sort communities and collections in-memory using a comparator
DSpace/DSpace pull request #1684
Opened 2017-03-23 14:53 UTC by tomdesair

Fix for https://jira.duraspace.org/browse/DS-3406 where the sorting of communities and collections happens in-memory and not by Hibernate.

2017-03-29 19:18 UTC, terrywbrady commented
@kshepherd , could you review this one?  The Jira ticket references some of your work.

2017-04-28 16:09 UTC, mwoodiupui reviewed
Other than one suspected typo, I think this is ready.

2017-04-28 16:09 UTC, mwoodiupui commented on dspace-api/src/test/java/org/dspace/content/comparator/NameAscendingComparatorTest.java
> +        when(dso2.getName()).thenReturn("b");
Should that be "dso1"?  dso2 is not used in this test.

2017-04-28 23:19 UTC, hardyoyo commented
I've tested this PR in vagrant-dspace and can confirm that collection and community names properly sort in an alphabetical order. @mwoodiupu has some good points about a few things, I'd not have any problem with approving this code after Mark's concerns have been addressed.

2017-04-29 16:11 UTC, hardyoyo commented
Based on my testing, I'm going to approve this, however, I will wait for @mwoodiupui to merge it, as he seems to have concerns, still.

2017-04-29 16:12 UTC, hardyoyo approved these changes

2017-05-02 11:35 UTC, pnbecker requested changes
I tested this in JSPUI and it works fine. There is just one issue left: currently it sorts communities/collections with a strange respect for small/capital letters.

2017-05-02 11:35 UTC, pnbecker commented on dspace-api/src/main/java/org/dspace/content/comparator/NameAscendingComparator.java
> +            return ObjectUtils.compare(dso1.getName(),dso2.getName());
I would suggest to either use `StringUtils.compareIgnoreCases(String, String)` here or to trim the Strings and convert them to either small or capital letters. Currently sorting the community/collections ends up in listing all communities/collection A-Z starting with capital letters first and then listing the communities/collection a-z starting with small letters. I would expect one alphabetical sequence, not two.

2017-05-02 16:00 UTC, tomdesair commented
Hi @pnbecker and @mwoodiupui 
My last commit addresses your comments: https://github.com/DSpace/DSpace/pull/1684/commits/e358cb84d1c4ade5056f3c35912adfddab660eec

Thanks for the thorough review!

2017-05-02 19:13 UTC, mwoodiupui approved these changes
+1 by inspection.  My concerns are addressed, and overall it looks well.

2017-05-03 11:54 UTC, hardyoyo approved these changes
+1 by review, and the tests were also revised to prove that compareToIgnoreCase does what it's supposed to do.

2017-05-03 11:55 UTC, hardyoyo approved these changes
Pascal's concerns have been addressed.

2017-05-03 12:36 UTC, pnbecker approved these changes
I haven't retested it, but the code looks good to me. Thanks a lot for the change!
+1

2017-05-03 12:37 UTC, merged

2017-06-09 20:39 UTC, tdonohue commented
This was cherry-picked to `master` in #1768