DS-3598: Allow localization of input-forms.xml with XMLUI
DSpace/DSpace pull request #1747
Opened 2017-05-18 07:55 UTC by AlexanderS

https://jira.duraspace.org/projects/DS/issues/DS-3598

2017-06-08 07:58 UTC, tomdesair requested changes
Hi @AlexanderS,

Could you limit the code changes to the changes required to solve DS-3598? That would make it a lot easier to review.

This implementation indeed aligns XMLUI with the JSPUI approach, but personally I don't like the JSPUI approach. If you have a repository that supports 6 different languanges, you will have to maintain 6 different input-forms files. A better approach would be to support message-keys in the input-forms.xml file, e.g.:

```
<field>
          <dc-schema>dc</dc-schema>
          <dc-element>title</dc-element>
          <dc-qualifier></dc-qualifier>
          <repeatable>false</repeatable>
          <label>Submission.submit.input.dc.title.label</label>
          <input-type>onebox</input-type>
          <hint>Submission.submit.input.dc.title.hint</hint>
         <required>Submission.submit.input.dc.title.required</required>
</field>
```

But that would be an backwards-incompatible change. So I think this PR is OK for DSpace 6.x, but I think we would need a better approach for master.

2017-06-08 07:58 UTC, tomdesair commented on dspace-xmlui/src/main/java/org/dspace/app/xmlui/aspect/submission/submit/DescribeStep.java
> +        String formFileName = I18nUtil.getInputFormsFileName(context.getCurrentLocale());
I think this is the only necessary change to fix DS-3598. So I'm not sure why we need all these other changes.

2017-06-08 07:58 UTC, tomdesair commented on dspace-xmlui/src/main/java/org/dspace/app/xmlui/aspect/submission/submit/DescribeStep.java
> +                    if (dcValue.getAuthority() == null || dcValue.getAuthority().equals(""))
It's not clear to me here why you changed "getWarning" to "getAuthority" and how this is related to DS-3598.

2017-06-08 09:46 UTC, AlexanderS commented on dspace-xmlui/src/main/java/org/dspace/app/xmlui/aspect/submission/submit/DescribeStep.java
> +        String formFileName = I18nUtil.getInputFormsFileName(context.getCurrentLocale());
Did you see, that this PR contains two commits? The first one is regarding DS-3598 and is comparatively small. The second one only contains whitespace changes.

If you review the commits in the github UI you may add a `?w=1` to the URL to ignore all whitespace changes.

2017-06-08 09:52 UTC, AlexanderS commented on dspace-xmlui/src/main/java/org/dspace/app/xmlui/aspect/submission/submit/DescribeStep.java
> +                    if (dcValue.getAuthority() == null || dcValue.getAuthority().equals(""))
This is actually not a change. The diff algorithm is not able to detect correct changes, due to the massive change of whitespaces. Before the change the file used a mixture of spaces and tabs and the indentation was distorted. But if you want, I can remove the second commit fixing the whitespace issues.

For review you want to look at the single commits and/or add `?w=1` to the URL.

2017-06-08 10:19 UTC, AlexanderS commented
Regarding the "better approach for master": This is not usable on master anyway, because it is part of XMLUI. I do not know, if the i18n system of dspace-angular will be compatible with the current message-key, but this is future for now.

2017-06-20 15:13 UTC, hardyoyo commented
here's a link to the whitespace-change-ignored diff: https://github.com/DSpace/DSpace/pull/1747/files?w=1

2017-06-22 11:23 UTC, tomdesair commented
👍 

I've tested the current approach and it works. The code also looks OK when using `?w=1`.

But as mentioned above, I think we need a better approach for DSpace 7 so that a repository administrator doesn't have to maintain an `input-forms.xml` file per locale.

2017-06-29 00:15 UTC, terrywbrady approved these changes
+1, tested locally by enabling webui.supported.locales = en, de, fr and creating input-forms_fr.xml with some simple changes.

2017-06-29 00:15 UTC, merged