DS-2687 Check group origin before deletion
DSpace/DSpace pull request #1846
Opened 2017-09-22 16:56 UTC by AndrewZWood

Jira Ticket: [When deleting a collection role the group is also deleted, which is not appropriate for non-system-created groups](https://jira.duraspace.org/browse/DS-2687?jql=project%20%3D%20DS%20AND%20resolution%20%3D%20Unresolved%20AND%20text%20~%20%22group%20deleted%22%20ORDER%20BY%20priority%20DESC%2C%20updated%20DESC)

This work utilizes the Group.Permanent property and a syntactical check function on the group name during the community/collection deletion flow, before the group is deleted, to verify that the group is 1. Not the system Administrator or Anonymous group & 2. To verify that the group is still system created by matching on the naming convention in which system groups are created. Deletions of the system Administrator group,  the system Anonymous group, and user created groups via the community collection deletion flow is not appropriate behavior.

2017-11-15 13:50 UTC, tomdesair requested changes
Only small remarks

2017-11-15 13:50 UTC, tomdesair commented on dspace-api/src/main/java/org/dspace/content/CollectionServiceImpl.java
> +import org.dspace.xmlworkflow.Role;
Do we need this import? We should not use any workflow implementation specific classes.

2017-11-15 13:50 UTC, tomdesair commented on dspace-api/src/main/java/org/dspace/eperson/Group.java
> +        String pattern = "^(COMMUNITY|COLLECTION)_[A-Fa-f\\-0-9]+_[A-Z_0-9]+";
In the future, we might want to make this more robuts by defining and setting an additional group property when creating groups.

2017-11-17 19:42 UTC, hardyoyo requested changes
I agree with Tom Desair, this could be made more robust with a more substantial refactor... however, this code does address a significant bug, using what we have now. It's good enough for now. Tom's also right, the xmlworkflow.Role import looks to be unused, it should be removed. That should be a quick and easy change.

2017-11-17 21:02 UTC, hardyoyo approved these changes

2017-11-17 21:28 UTC, hardyoyo commented
tested in Vagrant-DSpace, confirmed working

2018-05-29 14:27 UTC, tomdesair approved these changes

2021-09-03 20:34 UTC, tdonohue commented
Closing, as this appears to be fixed slightly differently in 7.0.  This 6.x version looks outdated & would require updates

2021-09-03 20:34 UTC, closed without merging