[DS-3762] fixed test for subCommunities
DSpace/DSpace pull request #1898
Opened 2017-12-13 16:47 UTC by Raf-atmire

This PR fixes the test on the /communities/search/subCommunities?parent=UUID endpoint as described by @abollini. cfr: https://github.com/DSpace/DSpace/pull/1893

2017-12-19 16:11 UTC, tomdesair requested changes
I just have some minor remarks to make the tests more clear.

2017-12-19 16:11 UTC, tomdesair commented on dspace-spring-rest/src/test/java/org/dspace/app/rest/CommunityRestRepositoryIT.java
> +        Community child12 = CommunityBuilder.createSubCommunity(context, parentCommunity)
@Raf-atmire The naming suggests that this Community is a sub-community of `child1`, but it's not. Can you rename this variable to `child2`?

2017-12-19 16:11 UTC, tomdesair commented on dspace-spring-rest/src/test/java/org/dspace/app/rest/CommunityRestRepositoryIT.java
>                  .andExpect(jsonPath("$._embedded.communities", Matchers.not(Matchers.containsInAnyOrder(
1. Please add a comment here that you are checking that the following communities are not present.
2. You should not use `containsInAnyOrder` to check something is not present. You should use
```
not(anyOf(
   hasItem(...),
   hasItem(...),
   hasItem(...) 
))
```

2017-12-19 16:11 UTC, tomdesair commented on dspace-spring-rest/src/test/java/org/dspace/app/rest/CommunityRestRepositoryIT.java
>                  .withName("Sub2 Community")
This would be sub-community 3.

2018-01-11 14:46 UTC, tomdesair approved these changes

2018-01-16 11:12 UTC, abollini requested changes

2018-01-16 11:12 UTC, abollini commented on dspace-spring-rest/src/test/java/org/dspace/app/rest/CommunityRestRepositoryIT.java
> +        getClient().perform(get("/api/core/communities/search/subCommunities/")
this is unexpected... the URL should be /api/core/communities/search/subCommunities without the final /
should we reject such request?

2018-01-16 11:12 UTC, abollini commented on dspace-spring-rest/src/test/java/org/dspace/app/rest/CommunityRestRepositoryIT.java
> +        getClient().perform(get("/api/core/communities/search/subCommunities/")
without the final /

2018-01-16 11:12 UTC, abollini commented on dspace-spring-rest/src/test/java/org/dspace/app/rest/CommunityRestRepositoryIT.java
> +        getClient().perform(get("/api/core/communities/search/subCommunities/")
without the final /

2018-02-15 16:57 UTC, abollini approved these changes

2018-02-15 16:57 UTC, merged