DS-4065: resource policy aware REST API hibernate queries
DSpace/DSpace pull request #2275
Opened 2018-11-30 16:35 UTC by J4bbi

NOT FULLY WORKING

This is an unfinished work in progress focusing on the REST ["items" endpoint](https://github.com/DSpace/DSpace/blob/4bfa0e27d5af40c8e5662e0db3b0059da385648b/dspace-rest/src/main/java/org/dspace/rest/ItemsResource.java#L149-L203).

As has been [discussed](https://github.com/DSpace/DSpace/pull/1879#issuecomment-340797819) in PR https://github.com/DSpace/DSpace/pull/1879 the DSpace 6 REST API checks resource policies in memory. Moreover this breaks the limit/offset functionality because a set number of results are retrieved and of those anywhere between none and all are withheld pending authorisation checks.  (see [DS-4065](https://jira.duraspace.org/browse/DS-4065))

This PR ports the code for the DSpace 7 REST API to from [PR 1879](https://github.com/DSpace/DSpace/pull/1879)

There is currently a problem with forming the Hibernate query correctly. In the resource policy aware query [findAllAuthorized](https://github.com/J4bbi/DSpace/blob/d75d97e2a65f047f75f4d62f9bdf70a5ad9918b7/dspace-api/src/main/java/org/dspace/content/dao/impl/ItemDAOImpl.java#L310-L337)  the following condition has been commented out: 

       `" AND (r.epersonGroup.id IN (:groupIdList) OR r.eperson.id = :currentUserId)" +`

with the groupIdList parameter being defined as

```
       LinkedList<UUID> list = new LinkedList<>();
        for(Group group: groups){
            list.add(group.getID());
        }
        query.setParameter("groupIdList", list);
```

because else 

```
java.lang.ClassCastException: java.util.LinkedList cannot be cast to java.util.UUID
 	at org.hibernate.type.descriptor.java.UUIDTypeDescriptor.unwrap(UUIDTypeDescriptor.java:37)
 	at org.hibernate.type.PostgresUUIDType$PostgresUUIDSqlTypeDescriptor$1.doBind(PostgresUUIDType.java:76)
 	at org.hibernate.type.descriptor.sql.BasicBinder.bind(BasicBinder.java:93)
 	at org.hibernate.type.AbstractStandardBasicType.nullSafeSet(AbstractStandardBasicType.java:284)
 	at org.hibernate.type.AbstractStandardBasicType.nullSafeSet(AbstractStandardBasicType.java:279)
 	at org.hibernate.param.NamedParameterSpecification.bind(NamedParameterSpecification.java:66)
 	at org.hibernate.loader.hql.QueryLoader.bindParameterValues(QueryLoader.java:612)
 	at org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:1897)
 	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1858)
 	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1838)
 	at org.hibernate.loader.hql.QueryLoader.iterate(QueryLoader.java:518)
 	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.iterate(QueryTranslatorImpl.java:399)
 	at org.hibernate.engine.query.spi.HQLQueryPlan.performIterate(HQLQueryPlan.java:284)
 	at org.hibernate.internal.SessionImpl.iterate(SessionImpl.java:1292)
 	at org.hibernate.internal.QueryImpl.iterate(QueryImpl.java:68)
 	at org.dspace.core.AbstractHibernateDAO.iterate(AbstractHibernateDAO.java:247)
 	at org.dspace.content.dao.impl.ItemDAOImpl.findAllAuthorized(ItemDAOImpl.java:336)
 	at org.dspace.content.ItemServiceImpl.findAllAuthorized(ItemServiceImpl.java:1303)
 	at org.dspace.rest.ItemsResource.getItems(ItemsResource.java:174)
 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 	at java.lang.reflect.Method.invoke(Method.java:498)
```

where and how Hibernate is told to expect a LinkedList < UUID >  and not a single UUID is currently beyond me. But as far as I can understand that's the single current problem.

2018-11-30 16:46 UTC, mwoodiupui commented
Try http://docs.jboss.org/hibernate/core/3.2/api/org/hibernate/Query.html#setParameterList%28java.lang.String,%20java.util.Collection%29

2018-12-04 11:42 UTC, J4bbi commented
I've tested the current commit: 314a844 by submitting a four items and placing one of them in a restricted collection.

`curl -v -X POST --data "email=testing@testing.com&password=testing" http://localhost:8080/rest/login`

use cookie id from login:
`curl -v --cookie "JSESSIONID=01D380A3886A8799D499292DD33199CA" http://localhost:8080/rest/items?limit=4`

the restricted item is withheld but for some reason the restricted item is the last one in the order of items even though it was the second item to be created.

2018-12-18 17:45 UTC, terrywbrady requested changes
@J4bbi , I have a large collection with a number of items restricted to a particular group.

I installed this PR on my server and tested a metadata query (/filtered-items) as (1)an admin (2)unauthenticated and (3)as a user with no group permissions.

I expected the /filtered-items query to return fewer results when I am not authenticated as an admin. The unfiltered result counts seem unchanged with this code in place.

Is my expectation correct that I should see a smaller count from this query?  Please update the PR with a recommended way to test/verify the changes.

I will do some additional testing with Postman to see if I can verify differences in retrieval counts.

If I remember correctly, in addition to the authorization checks this PR also includes a fix for the way that the offset value is used.  Would it be possible to submit that smaller fix as a separate PR?

Since you are changing the Group object in this PR, I will want to request that a couple of additional reviewers take a look at the changes.

2018-12-19 10:37 UTC, J4bbi commented
@terrywbrady thanks for taking this on

My understanding is that the filtered-items endpoint uses the itemService findByMetadataQuery method https://github.com/DSpace/DSpace/blob/d75d97e2a65f047f75f4d62f9bdf70a5ad9918b7/dspace-rest/src/main/java/org/dspace/rest/FilteredItemsResource.java#L132

which in turn uses the itemDAO findByMetadataQuery method https://github.com/DSpace/DSpace/blob/d75d97e2a65f047f75f4d62f9bdf70a5ad9918b7/dspace-api/src/main/java/org/dspace/content/ItemServiceImpl.java#L1037

Unlike other find methods of itemDAO a query is not built but a Criteria created
https://github.com/DSpace/DSpace/blob/314a84485ce20635517a91e7e621ff53c3e535da/dspace-api/src/main/java/org/dspace/content/dao/impl/ItemDAOImpl.java#L148

The PR does not affect these to my knowledge.

However, the findAllAuthorized method has been changed

https://github.com/DSpace/DSpace/blob/314a84485ce20635517a91e7e621ff53c3e535da/dspace-api/src/main/java/org/dspace/content/dao/impl/ItemDAOImpl.java#L310 

and it is used by the /items REST endpoint when responding to a GET request

https://github.com/DSpace/DSpace/blob/d75d97e2a65f047f75f4d62f9bdf70a5ad9918b7/dspace-rest/src/main/java/org/dspace/rest/ItemsResource.java#L174

I assumed this would be the simplest way to test this functionality. GET requests for items.

To test this you can make GET requests to the /items endpoint either as 1) anonymous, 2) group user like you mention or 3) administrator.

2018-12-19 19:44 UTC, terrywbrady approved these changes

2018-12-19 19:46 UTC, terrywbrady commented
@J4bbi , Thanks for the explanation.  This has helped me to better understand the purpose of the PR.

Calls to ` itemService.isItemListedForUser(context, dspaceItem)` will be replaced by `itemService.findAllAuthorized(context, limit.intValue(), offset.intValue())`, 

The total number of items returned will be the same.  The visible difference will be in the pagination of results.  

Without this fix, when the page size is small, the existing code may return pages of results that contain gaps in results.  (Note: this issue is easier to see on a fresh restart of a server.  The loading of the hibernate cache can cause restricted items to fall to the end of this list which makes the problem difficult to visualize.)

The results of this PR are much easier to prove in a small repository with several restricted or private items. 
- The following AIP files could be helpful in reproducing the issue: https://github.com/DSpace-Labs/AIP-Files/blob/master/dogAndReport.zip
- View all items /rest/items?limit=5.  Paginate through all items.  Note that some pages have fewer than 5 items.

Once this change is merged, it would be interesting to see a similar change to the findByMetadataQuery.

2018-12-21 11:20 UTC, J4bbi commented
I should not that equivalent changes can be made to the bitstreams endpoint before a merge is made.

2021-06-21 09:43 UTC, alanorth commented
Looks good to me. I confirmed this issue on the current DSpace 6.3 Demo as well as our own DSpace 6.3 production instance. Here is a simple reproducer on the public DSpace 6.3 Demo server:

 ```console
$ curl -s -H "Accept: application/json" "https://demo.dspace.org/rest/items?offset=0&limit=5" | jq length
5
$ curl -s -H "Accept: application/json" "https://demo.dspace.org/rest/items?offset=0&limit=5" | jq '.[].handle'
"10673/4"
"10673/3"
"10673/6"
"10673/5"
"10673/7"
# log into DSpace Demo XMLUI as admin and make one item private (for example 10673/6)
$ curl -s -H "Accept: application/json" "https://demo.dspace.org/rest/items?offset=0&limit=5" | jq length       
4
$ curl -s -H "Accept: application/json" "https://demo.dspace.org/rest/items?offset=0&limit=5" | jq '.[].handle' 
"10673/4"
"10673/3"
"10673/5"
"10673/7"
```

The result set which includes a private item is clearly incorrect: we are asking for a `limit` of five items starting at `offset` 0, but we only get four items. The REST API is counting the private item internally, but not taking that into account when returning the resulting items.

@J4bbi's fix here works as expected in our DSpace 6.3 staging environment: when a result set includes private items they are excluded from the REST API's internal item count and the number of items returned is the number specified in `limit`.

P.S. @J4bbi you should update the title of your latest commit message so it matches the GitHub issue title. It's way more helpful to see meaningful commit messages when looking in git history than having to go look on GitHub or Jira.

2021-06-24 20:56 UTC, J4bbi commented
Okay, so that's +3. What do you think @kshepherd ?

2021-09-18 13:09 UTC, J4bbi commented
@tdonohue , I will try to answer the issues you've raised the best I can. It's been almost three years since the PR was made and I must stress that I am not the author of the code.

I came across what I consider a serious bug of the REST api that it will internally fetch everything, load into memory and then filter. See for instance this excerpt from Items:

https://github.com/DSpace/DSpace/blob/b53f351e03613cc67420293be5e908df73ea764c/dspace-rest/src/main/java/org/dspace/rest/ItemsResource.java#L164-L187

here `dspaceItems` loads all items unfiltered and a loop appends items to an array based on a condition.

This is neither efficient nor effective to be honest. It loads everything into app memory and inconsistently returns results to the user. User has no way of navigating the REST API blindly, getting less results than _limit_ does **NOT** imply the end of possible results meaning users have to probe beyond the paginated < _limit_ page of results.

I ported/copied code from #1879 which was **NOT** merged into the main branch. Instead #1976 was merged.

Unfortunately I don't have time right now to review that PR or what the differences are between the two PRs, apologies.

I think that this PR adds the necessary findAuthorized methods which necessitates some changes to the Group, Collection classes etc.

I don't understand what you mean by wanting to be sure the changes are "compatible with all the Java API changes made in DSpace 7.0" in my understanding 7 is a complete refactoring and 6.x REST api therefore can not be compatible. My understanding that the code in this PR was rejected for 7.and a PR for 7 would be rejected again.

2021-09-20 14:59 UTC, tdonohue commented
@J4bbi : To clarify my comment...when I was talking about the "Java API" in my comment, I was referencing the number of `dspace-api` level changes in this PR.  Only ~37 lines of code in this PR modify the `dspace-rest` module, and all the rest modify our core `dspace-api` classes.  While v6 REST API and v7 REST API are 100% incompatible, there is still a *lot* of similarities between the v6 `dspace-api` and v7 `dspace-api`.  

So, my question was more around where we planned to "port" these changes to v7, as it's worth noting that in 7.0, we *still have* the deprecated v6 REST API  (so, yes, there's two REST APIs: the main required one, and the v6 one if you need it for backwards compatibility with scripts you built for that v6 REST API).  That said, if others feel this PR should only be applied to 6.x, I'm OK with it (since this older REST API is being phased out).  I'm just pointing out the fact that, without a way to port this to 7.x, these same issues will exist in the deprecated, v6 REST API that comes with 7.x.

2023-07-06 19:15 UTC, closed without merging