DS-4189 Enhance configuration by environment variables
DSpace/DSpace pull request #2373
Opened 2019-03-15 02:15 UTC by pnbecker

https://jira.duraspace.org/browse/DS-4189

To test:
```
export DSPACE__FOO=bar
/dspace/bin/dspace dsprop -p dspace.foo
```

2019-03-15 02:16 UTC, pnbecker commented
Unfortunately this cannot be backported as it requires Apache Commons Configuration 2 which is available as of DSpace 7.

2019-03-15 15:34 UTC, terrywbrady commented
I will give this a test and report my results.  I have a couple initial comments.

If this could not be implemented in DSpace 6, I presume we will use another technique (probably sed ... > local.cfg) for DSpace 6.  We can introduce different initialization scripts for each version of DSpace.

We have at least one variable that uses camel case `dspace.baseUrl`, so I do not think that we should translate upper case to lower case for property names.

2019-03-15 16:02 UTC, terrywbrady requested changes

2019-03-15 16:04 UTC, terrywbrady requested changes
Aside from the lower-case issue I mentioned, this code looks good.  I think this is the optimal approach for passing there properties into a container.

I tested locally and the changes work as expected.

For the earlier branches (DSpace 6, etc), we will implement a less-optimal solution for Docker purposes.

2019-03-15 16:42 UTC, tdonohue commented on dspace-services/src/main/java/org/dspace/servicemanager/config/DSpaceEnvironmentConfiguration.java
> +            String lookup = StringUtils.lowerCase(StringUtils.replace(key, "__", "."));
@pnbecker : Overall, this entire PR is a nice idea.  But, yes, we have a lot of configurations with mixed case (not all are even camel case).  For example, we have many configurations which mention a class name in their key (with mixed caps).  The media filter configs are a good example of this: https://github.com/DSpace/DSpace/blob/master/dspace/config/dspace.cfg#L370-L391

Unfortunately, I _believe_ Apache Commons Configuration is case sensitive.  I did some quick searching around on whether there's a way to make it case insensitive, and I'm not finding anything yet.  (That said, if we could find a way to make it case insensitive, then this lowercasing option would be wonderful.)

2019-03-15 18:25 UTC, pnbecker commented
I‘ll change this to be case sensitive. That is an easy task.

2019-03-15 19:33 UTC, terrywbrady commented
Fyi... I propose the following changes to our docker compose repo to accompany this change.

https://github.com/DSpace-Labs/DSpace-Docker-Images/pull/97

2019-03-17 23:29 UTC, pnbecker commented
@terrywbrady @tdonohue I made the changes requested. The configuration now works case sensitive. I tested it with dspace.baseURL and dspace.baseUrl and dspace.name.

2019-03-17 23:32 UTC, pnbecker commented on dspace-services/src/main/java/org/dspace/servicemanager/config/DSpaceEnvironmentConfiguration.java
> +            String lookup = StringUtils.lowerCase(StringUtils.replace(key, "__", "."));
I changed this to be case sensitive.

2019-03-18 15:00 UTC, terrywbrady approved these changes

2019-03-18 22:03 UTC, terrywbrady submitted a review, later dismissed
Since my last review, I discovered that we also need a mechanism to set properties containing a dash.  I was attempting to set `sword-server.enabled=true` and I discovered a similar issue to the one we discovered with periods.

I propose that we map `__dash__` to `-`.

I would be open to a different mapping.

The following PR illustrates why this additional enhancement will be needed.

https://github.com/DSpace-Labs/DSpace-Docker-Images/pull/98

2019-03-19 15:04 UTC, tdonohue commented
The code here is looking good overall.  Since @terrywbrady points out there are additional problem characters, we may want to come up with a more standard replacement strategy (which could cover other problem characters, if any arise).  So, as suggested by @terrywbrady , we could consider a standard replacement format like:

* `__dash__` to `-`
* `__dot__` to `.`

As-is, this PR is definitely specific to Apache Commons Configuration v2, as it relies on the concept of `ConfigurationBuilders` (which was introduced in that release, see [Migrating to 2.0](https://commons.apache.org/proper/commons-configuration/userguide/upgradeto2_0.html#Creating_Configurations)). So, I'm not sure this can be backported -- but it seems like a good solution for DSpace 7.x and above.

2019-03-19 22:47 UTC, pnbecker commented
I'm not a friend of so long environment variable names: `sword__dash__server__dot_enabled`, `dspace__dot_name`. How many properties do we have that contain any other characters than letters, numbers, dots and underlines? How many properties do we have that contain dashes? Could we think about renaming a few for DSpace 7 and create a rule to use letters, numbers, dots and dashes only?

2019-03-20 13:11 UTC, terrywbrady commented
I do not think we should rename properties.  I think we should keep the property names constant across DSpace versions

I agree that my first proposal would create long keys.  We could go with `___ -> -` and `__ -> .` or `_P_ -> .` and `_D_ -> -` (Period and Dash).

2019-03-21 16:50 UTC, tdonohue commented
Just a quick note. I agree here with @terrywbrady. I don't think we should rename properties to please Docker. I'd rather we come up with a reasonable replacement strategy.  

While I definitely understand the desire to keep environment variables short, I think we also need to consider the fact that many (most?) people using Docker may not even use these environment variables (beyond the default ones pre-set for them to initialize their Docker environment).  So, readability/length of the environment variables may not be a major concern if most users are not even aware of them.

2019-03-21 18:02 UTC, terrywbrady commented
We had a quick chat on Slack and decided to go with the following replacement code for consistency.

- `__D__` -> `-`
- `__P__` -> `.`

2019-03-21 21:05 UTC, terrywbrady commented
## Output to demonstrate that the change is in place 
```
$ winpty docker exec -it dspace //bin/bash
root@a9d8eefce1d3:/usr/local/tomcat# env|grep __
swordv2__D__server__P__path=swordv2
dspace__P__dir=/dspace
swordv2__D__server__P__collection__P__url=http://localhost:8080/swordv2/collection
swordv2__D__server__P__enabled=true
swordv2__D__server__P__url=http://localhost:8080/swordv2
dspace__P__hostname=localhost
dspace__P__baseUrl=http://localhost:8080
sword__D__server__P__enabled=true
dspace__P__name=DSpace Started with Docker Compose
swordv2__D__server__P__servicedocument__P__url=http://localhost:8080/swordv2/servicedocument
db__P__url=jdbc:postgresql://dspacedb:5432/dspace
root@a9d8eefce1d3:/usr/local/tomcat# cat /dspace/config/local.cfg
# ------------------------------------------------------------------------
# This file contains the localized properties for published DSpace images.
# See https://github.com/DSpace-Labs/DSpace-Docker-Images for usage information.
# ------------------------------------------------------------------------
dspace.dir = /dspace
db.url = jdbc:postgresql://dspacedb:5432/dspace
dspace.hostname = localhost
dspace.baseUrl = http://localhost:8080
root@a9d8eefce1d3:/usr/local/tomcat# /dspace/bin/dspace dsprop -p sword-server.enabled
true
root@a9d8eefce1d3:/usr/local/tomcat# /dspace/bin/dspace dsprop -p swordv2-server.enabled
true

```

2019-03-21 21:05 UTC, terrywbrady commented
@tdonohue , @mwoodiupui , @pnbecker , could you give this a quick review?

2019-03-22 19:07 UTC, tdonohue approved these changes
👍 Overall, this looks good.  One minor inline note below about correcting an inline comment to better document the behavior of the new `dspaceenv` tag in `config-definition.xml`

2019-03-22 19:07 UTC, tdonohue commented on dspace/config/config-definition.xml
> +             dot, as Bash does not allow variables that contains dots in their names.-->
This comment is now slightly inaccurate, as this has been extended to both periods and dashes.  Might want to restate this like:
`<!-- Load Environment variables that contain two underlines in their names. Some DSpace configurations use
special characters in their key (e.g. periods and dashes) which are not supported in Bash. This provider translates "___P___" to periods and "___D___" to dashes in environment variables. -->`

2019-03-22 19:18 UTC, mwoodiupui approved these changes
+1 by inspection.

2019-03-22 19:48 UTC, merged