DS-4190. Word-break CSS class breaks words without hyphens in Firefox…
DSpace/DSpace pull request #2374
Opened 2019-03-15 11:11 UTC by J4bbi

… and Opera mini
This CSS class change creates hyphens in Firefox / Opera mini when breaking words.

2019-03-18 07:22 UTC, kshepherd requested changes
this looks great, thanks :) 
i'm +1, but just a note: the attribution for the CSS is a nice touch, but to keep things consistent with how other CSS is managed in dspace, removing the comment might keep things cleaner. do you mind making that additional commit to this PR?

2019-03-18 12:09 UTC, J4bbi commented
DS-2963 Word wrap and hyphenation in Item Full View
is the same issue

2019-03-18 23:29 UTC, kshepherd approved these changes

2020-03-26 19:19 UTC, nwoodward approved these changes
:+1: Tested and this looks good.

2021-08-12 02:10 UTC, merged

2021-08-12 02:10 UTC, kshepherd commented
merged, thanks @J4bbi