[DS-4191] fixed a bug that didn't allow discovery to be ran for a que…
DSpace/DSpace pull request #2377
Opened 2019-03-19 13:02 UTC by Raf-atmire

This PR aims to solve JIRA issue: https://jira.duraspace.org/browse/DS-4191
This PR will allow a discover query to be ran for a query that contains a singular bracket, this was broke in the regular code that was present.
However there is still an issue with the escaping of the query if multiple brackets follow each other as the regex doesn't seem to support this properly, for instance the query: ((dc.date.issued:2010 OR dc.date.issued:1990-02-13) AND (dc.title:Test OR dc.title:TestItem2))
I currently do not know how to properly fix that issue, if anyone has any proposals, please come forward with them.
This is however the way that it works in DSpace 6 and DSpace 6 suffers from the same bug as I described above with the multiple brackets.

2019-03-19 15:13 UTC, mwoodiupui commented
https://stackoverflow.com/questions/133601/can-regular-expressions-be-used-to-match-nested-patterns
Short answer:  no.  A regex is not the right tool:  "regular expressions can't count."

If we are going to allow the current ambiguity (a search can be for either a plain string or a Lucene match expression, without declaring which) then probably the best we can do is to attempt to classify the request using a full Lucene-syntax parser and either escape or not based on what we guess the request was.

An alternative would be to require the user to specify which type of query it is.

2019-03-19 19:52 UTC, tomdesair requested changes
I thought that in https://github.com/DSpace/DSpace/pull/2206 (https://jira.duraspace.org/browse/DS-4010) it was decided that

> we provide feedback to users to escape special characters [...] by using quotes.

Since brackets are special characters, they should be escaped with quotes. The tests you `@Ignore`'d are [failing for a reason](https://github.com/DSpace/DSpace/pull/2206#issuecomment-425192803) ;-)

Was there a specific reason to come back on this decision?

2019-03-19 20:30 UTC, mwoodiupui commented
Thank you for remembering and pointing out that issue, @tomdesair .

So, what we have now is that the search input is *always a Lucene expression*.  If you put quotes around the whole thing, it is a phrase search:  it can contain characters that are special to the expression parser, and the whole thing will be matched exactly or not at all.

2019-04-25 09:43 UTC, abollini commented
I agree with @tomdesair 
https://github.com/DSpace/DSpace/pull/2377#pullrequestreview-216384038
so I propose to close this PR and the related ticket adding a note to the REST contract about our decision, see
https://github.com/DSpace/Rest7Contract/pull/58

2019-07-10 21:17 UTC, tdonohue commented
Closing this PR, as the expectation is now documented in DSpace/Rest7Contract#58

2019-07-10 21:17 UTC, closed without merging