Small improvements to configurable entities
DSpace/DSpace pull request #2411
Opened 2019-04-25 13:48 UTC by benbosman

2019-04-25 15:05 UTC, abollini requested changes
the javadoc looks odd, can you double check please?

2019-04-26 07:33 UTC, benbosman commented on dspace-api/src/main/java/org/dspace/content/factory/ContentServiceFactory.java
> +     * @return the list of RelationshipTypeService
Sorry, this was indeed just a copy of the existing JavaDoc as it's a self-explaining methods.
I've updated the wording

2019-04-26 15:45 UTC, tdonohue approved these changes
👍 Looks good to me!  @abollini can you glance at this again?  It looks like all your feedback has been resolved.

2019-04-30 07:59 UTC, abollini approved these changes

2019-04-30 07:59 UTC, merged