Ds 4351 upgrade dependencies
DSpace/DSpace pull request #2619
Opened 2019-12-10 15:28 UTC by KevinVdV

JIRA: https://jira.lyrasis.org/browse/DS-4351

This PR will upgrade (among others) the following dependencies to a more recent version:
* spring boot to version 2
* spring to version 5
* hibernate to version 5.3 

A couple of notes on the changes:
* Mockito will complain & crash your tests if you mock something that doesn't need to be mocked, so I had to remove some unused mocked methods from the tests
* pageable.getOffset() now returns a long, so we had to cast this to an int on several places
* ControllerUtils.toResponseEntity() can no longer take "null" as second argument, you have to use new HttpHeaders() now.

2019-12-19 17:13 UTC, cwilper requested changes
@KevinVdV I'm glad to see these upgrades happening, thanks for taking it on.

I tried this branch locally today. Upon doing a fresh build + deploy, startup failed with an error:

```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory' defined in file [/Users/user/Work/dspace/community-7/dspace/config/spring/api/core-hibernate.xml]: Invocation of init method failed; nested exception is org.hibernate.cfg.beanvalidation.IntegrationException: Error activating Bean Validation integration
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1778)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:273)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
        at org.springframework.data.rest.webmvc.support.JpaHelper.setBeanFactory(JpaHelper.java:27)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeAwareMethods(AbstractAutowireCapableBeanFactory.java:1800)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1765)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593)
        ... 101 more
Caused by: org.hibernate.cfg.beanvalidation.IntegrationException: Error activating Bean Validation integration
        at org.hibernate.cfg.beanvalidation.BeanValidationIntegrator.integrate(BeanValidationIntegrator.java:137)
        at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:276)
        at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:467)
        at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:708)
        at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:724)
        at org.springframework.orm.hibernate5.LocalSessionFactoryBean.buildSessionFactory(LocalSessionFactoryBean.java:615)
        at org.springframework.orm.hibernate5.LocalSessionFactoryBean.afterPropertiesSet(LocalSessionFactoryBean.java:599)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1837)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1774)
        ... 112 more
Caused by: java.lang.NoClassDefFoundError: javax/el/ELManager
        at org.hibernate.validator.messageinterpolation.ResourceBundleMessageInterpolator.buildExpressionFactory(ResourceBundleMessageInterpolator.java:88)
        at org.hibernate.validator.messageinterpolation.ResourceBundleMessageInterpolator.<init>(ResourceBundleMessageInterpolator.java:47)
        at org.hibernate.validator.internal.engine.ConfigurationImpl.getDefaultMessageInterpolator(ConfigurationImpl.java:474)
        at org.hibernate.validator.internal.engine.ConfigurationImpl.getDefaultMessageInterpolatorConfiguredWithClassLoader(ConfigurationImpl.java:650)
        at org.hibernate.validator.internal.engine.ConfigurationImpl.getMessageInterpolator(ConfigurationImpl.java:397)
        at org.hibernate.validator.internal.engine.ValidatorFactoryImpl.<init>(ValidatorFactoryImpl.java:183)
        at org.hibernate.validator.HibernateValidator.buildValidatorFactory(HibernateValidator.java:38)
        at org.hibernate.validator.internal.engine.ConfigurationImpl.buildValidatorFactory(ConfigurationImpl.java:364)
        at javax.validation.Validation.buildDefaultValidatorFactory(Validation.java:103)
        at org.hibernate.cfg.beanvalidation.TypeSafeActivator.getValidatorFactory(TypeSafeActivator.java:501)
        at org.hibernate.cfg.beanvalidation.TypeSafeActivator.activate(TypeSafeActivator.java:84)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.hibernate.cfg.beanvalidation.BeanValidationIntegrator.integrate(BeanValidationIntegrator.java:131)
```

I also noticed this could use an update with latest master. It looks like it occurred prior to the first round of projections work, so there are quite a few conflicts at the moment.

2019-12-19 18:07 UTC, cwilper commented on pom.xml
> +        <spring.version>5.1.9.RELEASE</spring.version>
latest spring version is now 5.2.2, latest spring boot version is 2.2.2

2019-12-20 15:54 UTC, KevinVdV commented
@cwilper Thanks for your review. For the startup changes, could it be that you are using a tomcat 7 ? Because [spring 5 requires tomcat 8.5+](https://github.com/spring-projects/spring-framework/wiki/What%27s-New-in-Spring-Framework-5.x#jdk-8-and-java-ee-7-baseline)

Not all the version on this PR are the latest ones. We had to find some match of version where everything worked. Also noticing that spring 5.2.2 was released while we working with the current dependencies, I quickly attempted to bump the version here but ran into version issues again.

What I would suggest here is to merge this one (as the version differences are a really big jump, going from spring 4 to 5) & redo the upgrade of versions a bit later prior to the release (or just after ?) of 7.0. 

Ps: Noticed that the tests are failing with the latest master merge, will attempt to resolve these ASAP, but these shouldn't hold back testing / reviewing.

2019-12-21 22:56 UTC, cwilper commented
> @cwilper Thanks for your review. For the startup changes, could it be that you are using a tomcat 7 ? Because [spring 5 requires tomcat 8.5+](https://github.com/spring-projects/spring-framework/wiki/What%27s-New-in-Spring-Framework-5.x#jdk-8-and-java-ee-7-baseline)

Thanks for pointing that out. I will update Tomcat and re-try.

Also, I agree with keeping at versions that you can make work as a first step and getting that in before worrying about the very latest.

Side note: I have been updating to Java 11 in another branch, and noticed it will work a bit better with the latest mockito. Since your branch updates mockito as part of the Spring/boot update anyway, I think ultimately, it should go in before the Java 11 one. So I'll rebase when you're ready with this one.

2020-01-03 15:18 UTC, cwilper approved these changes

2020-01-03 15:28 UTC, cwilper commented
@KevinVdV I took another look after latest updates and running w/Tomcat 8.5+. It works for me locally now. 

I did notice two oddities, neither of which I feel is a show stopper for this PR but which should be addressed at some point, possibly here or a followup PR:

1) The "Properties" in the HAL browser are showing escaped json. The HTTP responses seem fine.  Here's a screenshot to show what I mean: https://s.put.re/RAxFeKEU.png

2) The catalina.out log displays the following warning just prior to printing the Spring Boot banner:

```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/user/Work/dspace/community-7/dspace/webapps/server/WEB-INF/lib/slf4j-log4j12-1.7.6.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/user/Work/dspace/community-7/dspace/webapps/server/WEB-INF/lib/log4j-slf4j-impl-2.11.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
```

2020-01-06 15:06 UTC, KevinVdV commented
@cwilper Thanks for taking a closer look at this, I didn't notice these things. I was able to resolve them quite quickly though. Can you quickly verify that these issues are gone on your end as well ?

2020-01-06 18:39 UTC, cwilper commented
@KevinVdV I just confirmed with latest code, both issues no longer occur for me locally. Thanks.

2020-01-07 17:22 UTC, tdonohue reviewed
@KevinVdV: Thanks for this work!  I gave it a quick code review & test today.  The tests all prove to be mostly successful (though I'm seeing Maven build warnings when running a simple `mvn package`, see inline comments below).  That said, the build succeeds & the resulting Spring Boot webapp seems to work great (at least based on some basic testing). More comments inline below.

2020-01-08 13:12 UTC, KevinVdV commented on pom.xml
> +                <version>1.9.5</version>
The dependency was pinned here because there was a version conflict with this jar. I removed the dependency here & excluded it on the bte dependency.

2020-01-08 13:13 UTC, KevinVdV commented on pom.xml
> +                <version>${log4j.version}</version>
Some duplicate dependencies snuck in somehow, I removed the duplicates & the warnings are gone now.

2020-01-08 13:13 UTC, KevinVdV commented on pom.xml
> +                <version>1.2</version>
Some duplicate dependencies snuck in somehow, I removed the duplicates & the warnings are gone now.

2020-01-08 13:13 UTC, KevinVdV commented
@tdonohue Thanks for your review, I took a look at the issues you mentioned & was able to resolve them.

2020-01-08 16:17 UTC, tdonohue approved these changes
👍 Retested today & this is working great for me!  Code looks good too.

As a sidenote to any other testers, please be aware that this makes a minor update to the HAL Browser.  So, if (like me) you initially see the HAL Browser Properties showing just `[object Object]`, do a *hard refresh* (Refresh + Ctrl) in your browser to tell it to reload the HAL Browser changes.  This initially threw me for a loop, but after a hard refresh, everything is working great!

2020-01-08 16:18 UTC, tdonohue commented
As this is at +2 and flagged as high priority, I'm going to merge immediately.  Thanks again @KevinVdV !

2020-01-08 16:18 UTC, merged