Dspase-OpenAIRE-Funders
DSpace/DSpace pull request #2655
Opened 2020-01-27 07:57 UTC by dimitrispie

2020-02-21 15:27 UTC, paulo-graca requested changes
Thank you @dimitrispie for this contribution. Looking at the code, it's very simple to review. I couldn't test it perhaps because of my java 11 ready system. My comment and major concern is related with the need to deal with lack or missing data which are missing in this PR.

2020-02-21 15:27 UTC, paulo-graca commented on dspace-api/pom.xml
> +        <dependency>
This PR is far behind, currently DSpace 7 requires at least Java 11 and it's not backward compatible. This PR should be upgraded.
I'm getting this compiling error:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project dspace-services: Compilation failure
[ERROR] DSpace2655_git/dspace-services/src/main/java/org/dspace/servicemanager/config/DSpaceConfigurationPlaceholderConfigurer.java:[27,8] cannot access java.lang.Object
[ERROR] bad class file: /modules/java.base/java/lang/Object.class
```

2020-02-21 15:27 UTC, paulo-graca commented on dspace-api/src/main/java/org/dspace/external/provider/impl/OpenAIREFunderDataProvider.java
> +        Project project = response.getResults().getResult().getMetadata().getEntity().getProject();
With this kind of chained gets, we might requesting data on NULL objects. I think the case of not having data, or parts of it, should be addressed. Perhaps throwing exceptions to deal with this later.

2020-02-21 15:27 UTC, paulo-graca commented on dspace-api/src/main/java/org/dspace/external/provider/impl/OpenAIREFunderDataProvider.java
> +    private String sourceIdentifier;
can you add java docs to describe this properties?

2020-02-21 15:27 UTC, paulo-graca commented on dspace-api/src/main/java/org/dspace/external/provider/impl/OpenAIREFunderDataProvider.java
> +        return 1;
1 ???

2020-10-20 21:33 UTC, tdonohue commented
This work/PR appears to be outdated / possibly "stalled".  I just wanted to note that #2816 (the ticket associated with this PR) was/is scheduled for 7.0 beta 5 (which is starting development now).  Therefore, @dimitrispie if this PR is able to be updated/cleaned up, I can work on getting additional reviewers.  If not, I may need to reschedule this work for 7.1 (as beta 5 will be the final beta prior to 7.0).

2020-12-04 15:48 UTC, paulo-graca commented
@tdonohue, @dimitrispie created this other https://github.com/DSpace/DSpace/pull/2987 Pull Request to address the changes. 
I've already ask him to to a recent pull since the code seams outdated in that PR.

2021-01-13 16:38 UTC, paulo-graca commented
Hi @dimitrispie , the source repository for this PR isn't available. I think it will be no longer possible to merge the code. Does it makes sense to close this PR?

2021-01-13 16:43 UTC, paulo-graca requested changes
The source repository isn't available. Does it makes sense to keep this PR?

2021-01-22 16:03 UTC, tdonohue commented
Closing as this PR seems outdated & unmaintained and it seems to be replaced by #2987

2021-01-22 16:03 UTC, closed without merging