Support itemService.getMetadata with virtual md field
DSpace/DSpace pull request #3002
Opened 2020-10-14 11:40 UTC by benbosman

## Description
When using e.g. itemService.getMetadata(item, "relation", "isAuthorOfPublication", null, Item.ANY, true); the virtual metadata is currently not returned. This is due to ItemServiceImpl not using virtual metadata when the schema is "relation".

## Instructions for Reviewers
The RelationshipMetadataServiceTest.java fails with the master code.
To support e.g. `itemService.getMetadata(publication, "relation", "isJournalOfPublication", Item.ANY, Item.ANY, true)`, the ItemServiceImpl should use virtual metadata when the schema is "relation".

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [ ] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [ ] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [ ] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [ ] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [ ] If my PR includes new, third-party dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [ ] If my PR modifies the REST API, I've linked to the REST Contract page (or open PR) related to this change.

2020-10-28 21:10 UTC, tdonohue requested changes
@benbosman : Gave this a quick look today and I noticed that the new Test added in this PR isn't using Builder classes, so it's not cleaning up after itself.  Could we update this test to use Builders?  Beyond that, the code changes here look reasonable (though haven't manually tested anything yet).

2020-10-28 21:10 UTC, tdonohue commented on dspace-api/src/test/java/org/dspace/content/RelationshipMetadataServiceTest.java
> +    public void testGetVirtualMetadata() throws SQLException, AuthorizeException {
Can we update this test method to use Builder classes?  Currently, it does not appear to be cleaning up after itself.

2020-11-02 15:37 UTC, paulo-graca approved these changes
Thank you @benbosman for adding this!

2020-11-20 15:53 UTC, tdonohue requested changes
@MarieVerdonck and @benbosman :  This looks correct now.  One very minor last thing to cleanup.  Since you switched the test class to extend `AbstractIntegrationTestWithDatabase` (which is fine by me), the class now should have a name ending in `IT` to ensure it runs with other Integration Tests.  Once that is cleaned up, I'm +1 this PR

2020-11-20 15:53 UTC, tdonohue commented on dspace-api/src/test/java/org/dspace/content/RelationshipMetadataServiceTest.java
> +public class RelationshipMetadataServiceTest extends AbstractIntegrationTestWithDatabase {
This file should now be renamed `RelationshipMetadataServiceIT` since it's been switched to an Integration Test instead of a Unit Test.

2020-12-01 18:55 UTC, tdonohue approved these changes
👍 Looks good to me now too. Thanks @benbosman and @MarieVerdonck !

2020-12-01 18:56 UTC, merged