Community admin should also be considered a Collection admin
DSpace/DSpace pull request #3034
Opened 2020-10-29 15:40 UTC by LucaGiamminonni

## Description
The Community admins should also be considered a Collection admins. Currently, however, if a user is a community he is not also considered as a collection admin.

## Instructions for Reviewers
Please add a more detailed description of the changes made by your PR. At a minimum, providing a bulleted list of changes in your PR is helpful to reviewers.

## Checklist
- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).

2020-11-06 16:06 UTC, tdonohue requested changes
@LucaGiamminonni : Overall, this code looks good, but the Tests need some minor cleanup (to use Builders).  Once they are using Builder classes, I'd be +1 this change as it looks correct to me.

2020-11-06 16:06 UTC, tdonohue commented on dspace-api/src/test/java/org/dspace/authorize/AuthorizeServiceTest.java
> +        EPerson eperson = ePersonService.create(context);
Both of these tests should be using `Builder` classes to create all content.  Using a `Builder` will ensure that the content created is *automatically* deleted after the test completes.  Currently, these tests are not cleaning up after themselves.

So, please update these tests to use `CollectionBuilder`, `CommunityBuilder` and `EPersonBuilder`.  Note that you also don't need to create the Admin group, as you can use `CollectionBuilder.withAdminGroup(Eperson)` instead.

2020-11-06 16:06 UTC, tdonohue commented on dspace-api/src/test/java/org/dspace/authorize/AuthorizeServiceTest.java
> +        groupService.addMember(context, administrators, eperson);
Same here, use Builders please.

Also, for full test completion, would you be willing to add a `testIsCommunityAdmin()` method here...as it seems to be missing & it'd be good to also prove that a Community Admin also results in that method returning `true`, while a Collection Admin results in that method returning `false`.

2020-11-16 15:51 UTC, abollini commented
@tdonohue these are Unit Test not integration test so the builder classes cannot be used here, or am I missing something?

2020-11-16 15:59 UTC, mwoodiupui commented
IMHO unit tests *should not* use Builders or any other live infrastructure.  An ideal unit test exercises only the unit under test, test scaffolding and JRE classes.

2020-11-16 16:05 UTC, tdonohue commented
@abollini and @mwoodiupui : These tests are *creating* Communities & Collections for testing purposes and they are *not* cleaning up (deleting) those Communities or Collections.  This is why I requested using Builders in order to auto-delete the Communities or Collections.  However, if we add in code to remove those objects that's also OK.  My main concern is that these tests seem to be creating objects that they are not deleting....and all tests should clean up after themselves.

2020-11-16 16:54 UTC, mwoodiupui commented
Again considering that these are *unit* tests, I would suggest that the problem is that they are creating persistent objects by any means at all.  A unit test should supply the unit under test with all of the fake services and stub objects it needs to operate, carefully controlling what those services provide to the unit and monitoring what the unit asks them to do.

2020-11-16 17:03 UTC, tdonohue commented
@mwoodiupui : While I completely agree with you conceptually...unfortunately, this is not a rule that our existing Unit Tests _currently follow_.  So, you are talking about a rule change in our development processes.  I do fully agree that we should change this rule at some point, but that's too difficult to do in the midst of (very active) DSpace 7 dev work.

All that said, in order to move this PR forward, there are two options for @LucaGiamminonni .  Either...
1. Remove the code which creates new Community/Collection/EPerson objects and replace entirely with Mocks (as @mwoodiupui notes this is more in line with what a unit test generally does)
2. OR, update the code in these tests to ensure the created Community/Collection/EPerson objects **also get deleted after the test is complete**. One way to do this is using `Builder` classes.  (I agree with both @mwoodiupui and @abollini that Unit Tests ideally should not be creating objects, but nearly all our existing Unit Tests already do so....therefore I'd accept this PR if it simply cleans up the objects after using them.)

2020-11-18 13:57 UTC, abollini commented
thanks @tdonohue we will add the objects cleanup "manually" in a finally block. The Builders are not usable in Unit Test because their automatic cleanup process is only used by Integration Test. I agree with @mwoodiupui and you that the current Unit Test approach in DSpace is not ideal and I would like to understand how to move in the right direction but as you say this is the current situation and we should address the large topic in a dedicated discussion. I'm going to add this point to the agenda for a Dev meeting

2020-12-01 20:17 UTC, tdonohue approved these changes
👍 Looks good now.  Thanks @LucaGiamminonni

2020-12-01 20:18 UTC, merged