Enforce that facet "filter-operator" is a valid value
DSpace/DSpace pull request #3098
Opened 2020-12-17 14:10 UTC by KevinVdV

## References
* Fixes #3027

## Description
If no valid operator is passed in a filter query the discovery endpoint will now result in a bad request.

In my original issue above I noted that this shouldn't be checked for dates, but I'm afraid dates will also have to follow these rules (contains is the default), because the java code has no way to tell if the field is a date or not.

## Instructions for Reviewers
Fire of a query similar to: {dspace.url}/api/discover/search/objects?sort=score,DESC&page=0&size=10&f.author=pujari,%20kb

This should result in a bad request since the operator would be "kb". Next use:

 {dspace.url}/api/discover/search/objects?sort=score,DESC&page=0&size=10&f.author=pujari,%20kb,contains

This should work as "contains" is a valid operator.

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [X] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [X] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [X] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [X] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [X] If my PR includes new, third-party dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [X] If my PR modifies the REST API, I've linked to the REST Contract page (or open PR) related to this change.

2021-01-11 22:52 UTC, tdonohue approved these changes
👍 Looks good to me. I also tested it and it works as described.  Thanks @KevinVdV !

2021-01-14 12:35 UTC, abollini requested changes
thanks @KevinVdV for this PR I agree with the proposed changes at the implementation level but I think the error code here should be 422. This because if the parameter is here and it is a string the error is more "conceptually" so according to what we have also recently discussed and summarized here https://github.com/DSpace/DSpace/issues/3093#issuecomment-745347787 422 looks more appropriate to me.

2021-01-14 12:35 UTC, abollini commented on dspace-server-webapp/src/main/java/org/dspace/app/rest/parameter/resolver/SearchFilterResolver.java
> +            throw new DSpaceBadRequestException(
I suggest to return an UnprocessableEntityException here

2021-01-14 12:35 UTC, abollini commented on dspace-server-webapp/src/test/java/org/dspace/app/rest/DiscoveryRestControllerIT.java
> +                   .andExpect(status().isBadRequest());
this should be a 422 (please fix also the comment)

2021-01-14 12:35 UTC, abollini commented on dspace-server-webapp/src/test/java/org/dspace/app/rest/DiscoveryRestControllerIT.java
> +                   //Will result in 404 status because of missing filter operator
please update the comment to reflect 400

2021-01-14 12:49 UTC, abollini commented
I noted that the rest contract doesn't list return code yet https://github.com/DSpace/Rest7Contract/blob/main/search-endpoint.md#matching-dspace-objects-search-results so it would be useful to also make a PR to add these details now that we are finalizing them

2021-01-21 12:10 UTC, KevinVdV commented
@abollini We fixed your test feedback & I created a PR for the rest contract here: https://github.com/DSpace/Rest7Contract/pull/154

2021-01-26 20:25 UTC, abollini requested changes
hi @KevinVdV  @MarieVerdonck  there is still a small inconsistency compared to the rest contract. When the request parameter is here without a filter operator 422 should be returned, see inline unresolved comments

2021-01-26 20:25 UTC, abollini commented on dspace-server-webapp/src/main/java/org/dspace/app/rest/parameter/resolver/SearchFilterResolver.java
> +            throw new DSpaceBadRequestException(
this comment has been not yet processed

2021-01-26 20:25 UTC, abollini commented on dspace-server-webapp/src/test/java/org/dspace/app/rest/DiscoveryRestControllerIT.java
> +                   .andExpect(status().isBadRequest());
this should be 422 as well as agreed in the rest contract

2021-01-27 14:52 UTC, KevinVdV commented
@abollini We fixed your latest feedback.

2021-01-28 14:37 UTC, abollini approved these changes

2021-01-28 14:37 UTC, abollini commented
thanks @MarieVerdonck @KevinVdV it looks perfect now

2021-01-28 20:02 UTC, merged