DS-1680 Handle user using the back button to change collection during ingest
DSpace/DSpace pull request #310
Opened 2013-10-02 11:08 UTC by gmh04

https://jira.duraspace.org/browse/DS-1680

2015-05-14 22:39 UTC, aschweer commented
I've marked this as 5.2 because the corresponding Jira issue has fix version = 5.2. However, given that this is still marked "work in progress", it may need to be rescheduled.

2015-05-18 17:57 UTC, hardyoyo commented
+1 rescheduling

2016-03-30 17:06 UTC, tdonohue commented
As noted in the ticket, this code looks like it may continually create new WorkspaceItems each time you hit the back button. Needs testing / verification.

2017-02-03 21:59 UTC, tdonohue requested changes

2017-02-03 21:59 UTC, tdonohue commented on dspace-xmlui/src/main/resources/aspects/Submission/submission.js
> +        var workspace = WorkspaceItem.create(getDSContext(), dso, true);
As noted above, this looks like it'd create a new WorkspaceItem each time you hit the backbutton. May need rework.

2017-02-21 17:59 UTC, tdonohue commented
Closing as this PR must be recreated on `dspace-6_x` branch. XMLUI has been removed from `master`. See this mailing list notice: https://groups.google.com/d/msg/dspace-devel/aEFqSn46ryM/iPRr_IMLCwAJ

2017-02-21 17:59 UTC, closed without merging