handle redirect for items not working - REST Implementation
DSpace/DSpace pull request #3194
Opened 2021-03-17 12:57 UTC by Raf-atmire

## References
* Fixes https://github.com/DSpace/DSpace/issues/3113

## Description
This PR fixes the REST side for the above mentioned issue.
It'll take the identifier given in all the handleProviders and it'll remove any known prefixes like "hdl:". This will ensure that the actual handle is used in each resolve method.

## Instructions for Reviewers

List of changes in this PR:
* Added a method in the HandleService to strip the prefixes from the handles
* Used this method in each of the three HandleProviders in both the supports and resolve methods

How to test this PR:
* Build and deploy the code
* Call the `/api/pid/find?id=hdl:{handle}` endpoint
* Verify that a "Location" header is present in the response with the Item's location in it

## Checklist

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies the REST API, I've linked to the REST Contract page (or open PR) related to this change.

2021-03-22 15:28 UTC, tdonohue requested changes
@Raf-atmire : Gave this a quick code review (haven't tested yet).  I think the code looks good overall, but the new method in HandleServiceImpl should have Unit Tests to verify it works as expected.  Once those are added, I'll give this another look & test.

2021-03-22 15:28 UTC, tdonohue commented on dspace-api/src/main/java/org/dspace/handle/HandleServiceImpl.java
> +    public String formatHandle(String identifier) {
Could we add a Unit Test to verify this is working as expected for all of the `IDENTIFIER_PATTERNS` you've defined?  Currently, we seem to only test that it works for "hdl:", and only from the REST API.  We should have some basic Unit tests for this method to ensure it returns the expected string when passed different `identifier` values.

Two other things to note about this method:
* I think it's improperly named. It's not *formatting* a Handle.  It's parsing the handle out of an identifier string. So, I think we should call this `parseHandle()` and describe it as "Parses/extracts the handle prefix/suffix from an identifier string"
* Also this needs an `@Override`

2021-03-26 21:50 UTC, tdonohue commented
@ybnd : Just a quick note, unit tests are showing a missing license header in `HandleServiceTest.java`.  Once you add the standard DSpace header this error should go way.  (The tests themselves look to succeed though)

2021-03-27 17:10 UTC, ybnd commented
@tdonohue oh shoot, sorry about that.

2021-03-30 14:49 UTC, tdonohue approved these changes
👍 Looks good now! Thanks @Raf-atmire and @ybnd !

2021-03-30 14:49 UTC, merged