Browse by prefix filter
DSpace/DSpace pull request #8210
Opened 2022-03-15 09:45 UTC by MarieVerdonck

## References
* Fixes https://github.com/DSpace/DSpace/issues/8203
* UI clarifications on filter functionality (now applied to both plain text and items browsing) will be addressed in PR of https://github.com/DSpace/dspace-angular/issues/1379
* Related to `/api/discover/browses/<:index-name>/items` [REST Contract](https://github.com/DSpace/RestContract/blob/main/browses.md), **needs to be altered** there as well, still states _"startsWith: the value to use to calculate the offset. Each value in the page will be greater or equals than the specified value"_

## Description
The 'items' browse (`/api/discover/browses/<:index-name>/items`) now also filters the results when a `startsWith` is added, rather than jumping to the page where items with that prefix (in `dc.title`) are located.

## Instructions for Reviewers
The browse by items with `startsWith`, e.g. [/browse/title?startsWith=T](https://demo7.dspace.org/browse/title?startsWith=T) => `/server/api/discover/browses/title/items?sort=dc.title,ASC&page=0&size=20&startsWith=T` should now filter its results:
- The results should only contain items (paginated) that have title starting with 'T'
- Results should start at first page (totalElement less than without startsWith because now filtered)

## Checklist
- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [ ] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies the REST API, I've linked to the REST Contract page (or open PR) related to this change.

2022-03-25 16:46 UTC, tdonohue requested changes
@MarieVerdonck and @antoine-atmire :  Overall, this code looks good & it works for me.  However, this PR currently includes some commented out code...and that should be cleaned up before we can merge it.

2022-03-25 16:46 UTC, tdonohue commented on dspace-api/src/main/java/org/dspace/browse/BrowseEngine.java
> +                // offset = getOffsetForValue(focusValue);
Should this commented out code be removed?

2022-03-25 16:46 UTC, tdonohue commented on dspace-api/src/main/java/org/dspace/browse/BrowseEngine.java
> +        // String orderField = dao.getOrderField();
Again, it looks like you've commented out code here, and on line 696 and 706.  Should these be removed?  It looks (to me) like the ordering may not be necessary in this `getTotalResults()` method, as it doesn't matter what order the results come back in.

2022-04-06 15:51 UTC, tdonohue approved these changes
👍 Thanks @MarieVerdonck and @antoine-atmire !  This now looks good to me.  Could one of you submit a PR to update the REST Contract (as noted in the description)?  Once that REST Contract PR is in place, I'll get this merged along with the REST Contract updates.

2022-04-06 16:27 UTC, MarieVerdonck commented
@tdonohue : PR to update rest contract to reflect these changes: https://github.com/DSpace/RestContract/pull/184 
startsWith is now filter for both item and plain-text browses (previously only for plain-text)

2022-04-06 17:15 UTC, tdonohue commented
Merging, as I just reviewed the REST Contract PR and also merged it https://github.com/DSpace/RestContract/pull/184  Thanks again @MarieVerdonck and @antoine-atmire !

2022-04-06 17:15 UTC, merged