Cst-5855 custom resource policies are duplicated if multiple upload configuration share the same access conditions
DSpace/DSpace pull request #8324
Opened 2022-05-30 10:03 UTC by ballarinie

* Fixes https://github.com/DSpace/DSpace/issues/8282

## Description
This PR fixes the bug involving the bitstream of a submitted item having duplicate access conditions when the selected ones are shared among multiple configurations.
Also, requests related to unconfigured and/or unavailable access conditions are now managed and rejected with 422 status code.
ITs have been implemented by previously changing the corresponding `access-conditions.xml` accordingly.
.
## Checklist
- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies the REST API, I've linked to the REST Contract page (or open PR) related to this change.

2022-06-08 13:22 UTC, corrad82-4s requested changes
@ballarinie , code overall looks good to me. I dropped a couple of minor notes. 
If you can, please add a comment with a couple of instructions about how this PR can be tested, if a correspondent angular PR is needed, etc.

2022-06-08 13:22 UTC, corrad82-4s commented on dspace-server-webapp/src/main/java/org/dspace/app/rest/submit/factory/impl/BitstreamResourcePolicyUtils.java
> +                found = true;
once found, we could break the for loop

2022-06-08 13:22 UTC, corrad82-4s commented on dspace-server-webapp/src/test/java/org/dspace/app/rest/WorkspaceItemRestRepositoryIT.java
> +        //Add
In my opinion, this comment is not 100% clear

2022-06-08 16:18 UTC, ballarinie commented
Fixed code according to @corrad82-4s 's comments.

About testing:
- to properly test the duplicated resource policy bug is solved, I simply replicated the steps Andrea Bollini https://github.com/DSpace/DSpace/issues/8282. Now, only one resource policy is going to be shown when checking those of the bitstream of the related archived item.
- this PR also denies patch operations that would add unconfigured and/or unavailable access conditions to the item during a submission. This could be tested via postman (quoting the workspaceitem-data-upload.md rest contract):
`curl --data '{[ { "op": "add", "path": "/sections/<:name-of-the-form>/files/<:file-idx>/accessConditions/-", "value": {name: "...", <wrong-access-condition>: ".."}}]}' -X PATCH ${dspace7-url}/api/submission/workspaceitems/<:id>`
Using an unconfigured/unexisting access-condition should bring to a 422 answer. This situation is not handled in the UI, but the list of the selectable access conditions is limited to those configured in the access-conditions.xml file.

2022-06-09 15:34 UTC, corrad82-4s approved these changes
@tdonohue Mi feedback has been addressed and instructions about how to test this PR have been added. I approve the work

2022-06-09 20:31 UTC, tdonohue approved these changes
👍 Thanks @ballarinie !  I tested this today by trying to reproduce the original bug, and I can no longer do so.  The code and tests also look good.

2022-06-09 20:31 UTC, merged