Ensure Local Filter services are autowired
DSpace/DSpace pull request #8421
Opened 2022-07-25 03:52 UTC by kshepherd

(WIP, will update this PR after CI tests have run)

2022-07-26 01:07 UTC, kshepherd commented
@tdonohue I have optimistically set a milestone of 7.4 as this bug is preventing item filters from working properly, and the fix is so simple. I hope that's OK.

2022-07-26 14:31 UTC, tdonohue commented
@kshepherd : perfectly OK.  Just a note for the future, you are welcome to pull any PR over to our currently active project board (which I just did for this one).  Doing so will ensure it's considered for the next release & will prompt me to find reviewers in the next dev meeting.  Since 7.4 is concentrating on bug fixes first, I think it makes perfect sense for this PR to get included in 7.4

2022-07-28 20:48 UTC, mwoodiupui requested changes
The explicit initializations should be removed, because those values will be replaced by Spring autowiring just after the constructor runs.

2022-07-28 23:05 UTC, kshepherd commented
@mwoodiupui Thanks, that was something I missed. Unfortunately, after making that change, the Unit Tests are failing again. So I'll have to dig in again.

2022-07-29 13:29 UTC, mwoodiupui commented
Just a note:  if you don't have that Item (for example, if you don't have *any* items because you created a fresh database) then it NPEs at TestLogicRunner:111.  Not an issue with this patch.

2022-07-29 13:41 UTC, mwoodiupui approved these changes
Looks right, runs to completion with the expected result.

2022-07-29 14:45 UTC, merged