Fix browse by title filter doesn't work with diacritics
DSpace/DSpace pull request #8435
Opened 2022-07-28 08:58 UTC by toniprieto

## References

* Fixes #8434

## Description

Change the default normalization of the indexed text used for sorting and filtering titles to strip the diacritics.

It is similar to the PR applied for filtering accented content in subject/author indexes: #2698

## Instructions for Reviewers

To test the changes:

* Publish an item with an accented title and another with an unaccented title. By example: "Número 1" and "Numero 2"
* Filter by title with value: "Número". Should return the two items.
* Filter by title with value: "Numero".  Should return the two items.

List of changes in this PR:
* Apply the StripDiacritics filter to the normalization of indexed titles
* Applies the same normalization to the user-input text when the user is filtering by title
* Include a new test to check the behavior with diacritics
* Correct two comments that I forgot to change in PR #2698

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies the REST API, I've linked to the REST Contract page (or open PR) related to this change.

2022-08-03 14:30 UTC, corrad82-4s requested changes
Overall this code looks good to me, I have just reported a Minor (possible) issue.

2022-08-09 12:02 UTC, toniprieto commented on dspace-api/src/main/java/org/dspace/browse/BrowseEngine.java
> +            if (scope.getBrowseIndex().getDataType().equals(OrderFormat.TITLE)) {
Change added to prevent NPEs. Thanks!

2022-08-09 13:41 UTC, corrad82-4s commented
@tdonohue , @toniprieto  after last change, code looks good to me.

2022-08-09 13:41 UTC, corrad82-4s approved these changes

2022-08-09 18:17 UTC, tdonohue approved these changes
👍 Thanks @toniprieto ! This looks correct to me and the ITs prove that it works as expected.

2022-08-09 18:17 UTC, merged