Further S3 large file optimization
DSpace/DSpace pull request #8500
Opened 2022-09-30 14:30 UTC by LucaGiamminonni

## References
* Fixes https://github.com/DSpace/DSpace/issues/7674
* Fixes https://github.com/DSpace/DSpace/issues/8570

This PR added further S3 improvements in addition to those introduced with https://github.com/DSpace/DSpace/pull/8060

- [X] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [X] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [X] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [X] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [X] If my PR includes new, third-party dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [X] If my PR modifies the REST API, I've linked to the REST Contract page (or open PR) related to this change.

2022-11-08 15:04 UTC, abollini commented
@LucaGiamminonni I noted that test class has been heavily modified and I understand that the changes were due to the the tied coupling needed to mock the internal behavior of the S3 client inherited from the existing implementation. In this way the test are a self-referential and more intended to demonstrate that the mocking is working as expected than that proof the real code is working... is not a failure of this PR but would be possible to revisit the test to be more effective? would be possible to use a mock S3 embedded/service? Can you take a look at https://docs.tiledb.com/main/how-to/backends/minio and see if it is possible to use it for testing purpose?

2022-12-09 16:56 UTC, tdonohue requested changes
@LucaGiamminonni : I gave this a code review today.  Overall the code looks good, but I have a few minor comments inline which I think should be fixed before this can be moved forward.

Unfortunately, I'm not able to test this myself as I don't have a testable S3 setup.  But, I'm hoping that @benbosman (or someone on his team) could find some time to give this a quick test.  Based on the integration tests though, this appears like it *should* work.

2022-12-09 16:56 UTC, tdonohue commented on dspace-api/pom.xml
> +            <version>2.13.2</version>
Should this have a `<scope>test</scope>` added?  It appears, to me, that we are not using this library in our code, but maybe it's required by the new `s3mock_2.13` library?  If so, we should make sure this is also limited to `test` scope.

2022-12-09 16:56 UTC, tdonohue commented on dspace-api/src/main/java/org/dspace/storage/bitstore/S3BitStoreService.java
> +                    attrs.put("size_bytes", objectMetadata.getContentLength());
Could we add tests for the changes to this `about()` method?  Codecov is saying that none of the newly added code in this method is tested.

2023-01-13 22:14 UTC, tdonohue commented on dspace-api/src/main/java/org/dspace/storage/bitstore/S3BitStoreService.java
> +                DigestInputStream dis = new DigestInputStream(in, MessageDigest.getInstance(CSA));
This is a false positive.  MD5 is only being used for checksums, not for encryption.

2023-01-13 22:15 UTC, tdonohue commented on dspace-api/src/main/java/org/dspace/storage/bitstore/S3BitStoreService.java
> +                    byte[] md5Digest = MessageDigest.getInstance(CSA).digest(IOUtils.toByteArray(in));
Same here. This is a false positive.  MD5 is only being used for checksums, not for encryption.

2023-01-13 22:54 UTC, tdonohue reviewed
@LucaGiamminonni : Gave this another review today.  The code itself looks good & the tests look good.  I'm not able to test the new S3 code, but I tried testing the fix for #8570.  Unfortunately, though, I'm not able to get a status other than CHECKSUM_MATCH in the `checksum_history` table.

I feel like I must be doing something wrong, but here's what I've tried:
1. First, I found a bitstream's assetstore location (`internal_id`) by running `select internal_id from bitstream where uuid='[bitstream-uuid]` in the database;
2. I went to the corresponding directory in the `[dspace]/assetstore/` and I created a "tmp" subdirectory and **moved** the bitstream file to that subdirectory.  (This should mean the bitstream is now "missing" as it's not in the correct directory)
3. I ran `./dspace checker -b [bitstream-uuid]`.
4. Back in the database I ran `select * from checksum_history where bitstream_id='[bitstream-uuid]';`  I found the most recent run, but it still says "CHECKSUM_MATCH".  (I thought it should now say "BITSTREAM_NOT_FOUND").

Overall, the code here looks good & looks like an improvement.  But, I'm not sure this fully fixes #8570, unless I'm misunderstanding something.

2023-01-18 11:37 UTC, toniprieto commented
@LucaGiamminonni @tdonohue About the checksum checker issue, in case it helps, there is a 6x PR that solve the same problem: https://github.com/DSpace/DSpace/pull/2160

It has an extra modification on [dspace-api/src/main/java/org/dspace/checker/CheckerCommand.java](https://github.com/DSpace/DSpace/pull/2160/files#diff-0e20910334231dc6e037c25d550acfbdbacdd287a6c4800a913522ba9fcfb1e7) that could solve the issue reported by Tim in the last comment.

Moreover, it has another modification similar to https://github.com/DSpace/DSpace/pull/8500/files#diff-ac4d9e325a8d736647418f4d16e4f7721cc0564eaa4565b0acb29b9b27a0764f for function `findByNotProcessedInDateRange`

I tested in a 6x instance and it seems to work ok.

2023-02-01 10:31 UTC, benbosman reviewed
I've also reviewed the code, and don't see any issues.

I will try to test the functionality with S3 as well

Thanks for the contribution

2023-02-14 21:03 UTC, tdonohue commented
Moving this to 7.6 as there's been no updates in the last month & there's feedback above to be resolved..  We've run out of time for 7.5, but I'd love to see this move forward for 7.6.

2023-04-13 21:05 UTC, tdonohue approved these changes
👍 Thanks @LucaGiamminonni !  I've verified this fixes the issues with checksum history now (described in #8570).  The code for S3 also looks good and the tests look good as well.

I'm not able to test this against a DSpace running in S3, so I'd appreciate it if @benbosman (or someone on his team) could run a quick test prior to merger.  But, the code looks good to me.

2023-06-08 15:20 UTC, abollini commented
hi @tdonohue I checked and our internal code that we use for hosted DSpace and the code in DSpace-CRIS is slightly different.
Mainly because in this PR we have further cleanup the code but we also have some additional capacities on our code that was introduced later and not included in this PR. So a real test would be better, @francescopioscognamiglio  will try to do tomorrow or early next week at latest

2023-06-08 15:31 UTC, tdonohue commented
@abollini : Thank you to you and @francescopioscognamiglio !  Once a test is complete, just comment back here to let me know how it goes.  I simply need verification that the updated S3 code in this PR is working well, as I have no way to easily test it myself.

2023-06-09 08:42 UTC, francescopioscognamiglio commented
Hi @tdonohue I have done the following tests using an S3 assetstore.
**Test of existing bitstreams:**
1. open an item with at least one bitstream
2. download the bitstream

**Test of a new bitstream:**
1. start a new submission
2. upload a bitstream
3. finish the submission
4. download the bitstream

2023-06-09 14:41 UTC, tdonohue commented
@francescopioscognamiglio : Thank you for the testing!  In that case, I will merge this for 7.6, as the code looks good to me & I previously verified it fixes the checksum checker bug... and just wanted verification that S3 was working.

2023-06-09 14:42 UTC, merged