Added input validation for new metadata field submissions & fixed some other bugs related to metadata fields
DSpace/DSpace pull request #8758
Opened 2023-03-30 17:03 UTC by alexandrevryghem

## References
* Fixes #8754

## Description
Added backend validation that checks if a dot is present in either the schema, element or qualifier. Sorted the retrieved metadata fields from the `/core/metadatafields/search/byFieldName` rest endpoint, to prevent the exact match from not being shown int the suggestion list (which lead to an error on Angular which prevents you from submitting a value for that field). And fixed pagination issues from `/core/metadatafields/search/byFieldName`.

## Instructions for Reviewers
List of changes in this PR:
* `MetadataFieldIndexFactoryImpl`
  * I added a new Solr field `fieldName_sort` that I used to sort the metadata fields retrieved by the `/core/metadatafields/search/byFieldName` rest endpoint (previously when you added more than 10 fields and completely rebuild Solr the exact match was always shown as the last field. Because Angular only checks if the field is present in the list of 10 fields who match the closest to the input you provided, and that the 11th metadata field is not send back to the user, the code marked the metadata field as invalid)
* `MetadataFieldRestRepository`
  * Replaced the value from `totalElements` with the actual value from the number of metadata fields who matched on Solr, instead of the size of the page (which is by default 10).
  * Fixed the `/core/metadatafields/search/byFieldName` pagination issues which made it impossible to change the size and the page you were on.
  * Added validation in the `createAndReturn` function to also check that the given string does not contain any dots.
* `MetadataSchemaRestRepository`
  * Added validation in the `createAndReturn` function to also check that the given string does not contain any dots.

**Guidance for how to test and review this PR:**
- Add a lot of `dc.subject.*` fields (so that you have more than 10 fields (or 20 if you don't use the linked Angular PR)) and rebuild the whole Solr index again.
- Test the [/core/metadatafields/search/byFieldName](http://localhost:8080/server/api/core/metadatafields/search/byFieldName?schema=dc&element=subject&qualifier=&query=&exactName=&embed=schema&size=2&page=1) rest endpoint and check that you can now change the current page and the page size. Also check that the `totalElements` is correct.
- In the UI go to `Edit Item > Metadata` check that the `dc.subject` field is shown as the first field.

## Checklist
- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [x] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

2023-04-27 13:15 UTC, abollini requested changes
hi @alexandrevryghem ,
thanks for your contribution, code looks good but the following things seem to be missing
- we need a RESTContract PR to record the agreed changes in the REST behavior (reject of special characters in creation, refuse to update anything than scope)
- I haven't found IT related to the pagination fix and the new scenario that should be checked in creation

2023-05-07 12:58 UTC, abollini commented on dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/MetadataSchemaRestRepository.java
> +        }
this is not appropriate as the endpoint exists, it is a semantic error in the syntactically valid request so it should be a 422

2023-06-02 17:45 UTC, tdonohue requested changes
@alexandrevryghem : Overall, this looks good and it works.  I've verified it aligns with the REST Contract & tested it with the frontend PR.  In my review of the UI PR, I've suggested a few other validation checks (for spaces and commas) in element/qualifier which I've added here as well.

Finally, I did find what looks to be a bug in the sorting.  The sorting works *better*.  However, when there's a null qualifier (no qualifier), I'd expect those to be sorted **at the top** (before any fields which have qualifiers).  It appears they are sorted **to the bottom**, which means that they **sometimes don't appear in suggestions.**

Here's an example... searching for "dc.subject" doesn't find the existing `dc.subject` field, because it's not sorted into the first 10 results:
![sorting](https://github.com/DSpace/DSpace/assets/483997/0ef06ee6-c2fa-478d-a7ad-62c316b21bae)

(But for fields where there's <10 results, it works OK.  For instance searching for "dc.type" will find `dc.type`, but it's last in the list)

Overall your sorting is an improvement.  But, it's not a complete fix yet.

2023-06-02 17:45 UTC, tdonohue commented on dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/MetadataSchemaRestRepository.java
> +        } else if (metadataSchemaRest.getPrefix().contains(".")) {
We also should check for commas, spaces and underscores... as those are all invalid in the UI.

2023-06-02 17:45 UTC, tdonohue commented on dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/MetadataFieldRestRepository.java
> +        } else if (metadataFieldRest.getElement().contains(".")) {
As I suggested in the UI PR, I think we should also check for commas and spaces.  Those should not be allowed in the element.

2023-06-02 17:45 UTC, tdonohue commented on dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/MetadataFieldRestRepository.java
> +        } else if (metadataFieldRest.getQualifier().contains(".")) {
As I suggested in the UI PR, I think we should also check for commas and spaces.  Those should not be allowed in the qualifier

2023-06-06 19:31 UTC, tdonohue approved these changes
👍 Thanks @alexandrevryghem !  You were correct, I forgot to previously re-index... after reindexing, the search-by-metadata-field on the Edit Item page works properly!

I've also verified that the improved validation is all working well.  Looks great!

2023-06-06 19:33 UTC, merged