fix bug: reset password from Admin Panel #8765
DSpace/DSpace pull request #8766
Opened 2023-04-06 09:32 UTC by Ma-Tador

## References
* Fixes ##8765

## Description
Changed the method responsible to handle register and reset password.

## Instructions for Reviewers
Disable reCaptcha check if the request is to reset password (because the user was already checked at registration).

List of changes in this PR:
Refactoring the createAndReturn method.

**Include guidance for how to test or review your PR.** 
    Log in as Admin
    Go to Access Control -> People -> Edit a Person -> Reset Password

2023-04-27 18:59 UTC, tdonohue commented
@Ma-Tador : I just realized this PR is failing our Checkstyle checks (it appears your IDE may have reformatted some of the code slightly and it fails checks). To see these failures locally you can run our checker from the commandline: https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide#CodeStyleGuide-Checkingcodestylefromcommandline

2023-05-01 18:48 UTC, tdonohue requested changes
@Ma-Tador :  Overall this looks good & I verified that your fixes **work**.  I also verified this bug does exist on `main` (but only when Captcha is enabled).

However, it looks like your editor / IDE has accidentally reformatted some of the code so that it no longer aligns with our [Code Style requirements](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).  This means that running a checkstyle is failing on this new code: `mvn -U checkstyle:check`   I've highlighted below where the main problems are.

If you can cleanup the code so that it passes Checkstyle, then I think this will be ready (presuming that all automated tests pass/succeed).  If you have any issues with getting this updated, please let me know...as I'd like to include this fix in 7.6 (which is due in June).

2023-05-01 18:48 UTC, tdonohue commented on dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/RegistrationRestRepository.java
> +
Remove trailing spaces.

2023-05-01 18:48 UTC, tdonohue commented on dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/RegistrationRestRepository.java
> +           } else if (accountType.equalsIgnoreCase(TYPE_REGISTER)) {
Please remove the indentation here before the `else if`. This can go back to how it was

2023-05-01 18:48 UTC, tdonohue commented on dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/RegistrationRestRepository.java
> +
This extra line can be removed

2023-05-02 10:20 UTC, Ma-Tador commented
Hi Tim, I am using NetBeans as IDE and I can not load the checkstyle into it to proper align with the DSpace checkstyle. Should I change to IntelliJ in order to have my code properly formatted as per DSpace checkstyle? Will the Intellij Community Edition work properly with the complexity of DSpace? (Spring Boot, JPA etc)
However, I removed the white space as you pointed, so I hopefully will pass the DSpace checkstyle.

2023-05-02 14:25 UTC, tdonohue commented
@Ma-Tador : You can use our Checkstyle checks in the NetBeans IDE.  See the instructions on the Code Style Guide page I linked to above: https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide#CodeStyleGuide-NetBeans

You can also run the checkstyle checks from commandline via Maven, if you don't want to run them in your IDE. https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide#CodeStyleGuide-Checkingcodestylefromcommandline

I can verify too that IntelliJ Community Edition (which is free) works perfectly well with DSpace 7.  However, you can continue to use Netbeans if you wish (At this time I think most core developers are using IntelliJ but there are a few who I know use Netbeans.)

In any case, it appears the Checkstyle issues are fixed (those tests passed).  However, now there is a test failure in  `RegistrationRestRepositoryIT`: 
```
Error:  Failures: 
Error:  org.dspace.app.rest.RegistrationRestRepositoryIT.registrationFlowWithNoHeaderCaptchaTokenTest(org.dspace.app.rest.RegistrationRestRepositoryIT)
Error:    Run 1: RegistrationRestRepositoryIT.registrationFlowWithNoHeaderCaptchaTokenTest:303 Status expected:<403> but was:<400>
Error:    Run 2: RegistrationRestRepositoryIT.registrationFlowWithNoHeaderCaptchaTokenTest:303 Status expected:<403> but was:<400>
Error:    Run 3: RegistrationRestRepositoryIT.registrationFlowWithNoHeaderCaptchaTokenTest:303 Status expected:<403> but was:<400>
```
Again, this can be reproduced locally (on your machine) by running the Integration tests locally via the instructions at: https://github.com/DSpace/DSpace/#running-tests

The good news is that I think the problem may be that the test itself is wrong.  It appears to be missing the required `accountTestType` param.  So, I think you can correct it by adding this:
```
.param(TYPE_QUERY_PARAM, TYPE_REGISTER)
```
To around line 301 (see how other nearby tests all include this same code): https://github.com/DSpace/DSpace/blob/main/dspace-server-webapp/src/test/java/org/dspace/app/rest/RegistrationRestRepositoryIT.java#L301

Once the Integration tests are passing, this can be merged.  Hopefully this simple change will fix things... but if not, then we may need to look closer at why the changed code isn't returning what that test expects.

2023-05-02 14:55 UTC, mwoodiupui commented
On Tue, May 02, 2023 at 07:25:28AM -0700, Tim Donohue wrote:
> @Ma-Tador : You can use our Checkstyle checks in the NetBeans IDE.  See the instructions on the Code Style Guide page I linked to above: https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide#CodeStyleGuide-NetBeans
> 
> You can also run the checkstyle checks from commandline via Maven, if you don't want to run them in your IDE. https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide#CodeStyleGuide-Checkingcodestylefromcommandline
> 
> I can verify too that IntelliJ Community Edition (which is free) works perfectly well with DSpace 7.  However, you can continue to use Netbeans if you wish (At this time I think most core developers are using IntelliJ but there are a few who I know use Netbeans.)

Didn't we have a file in some common format that encodes our style
rules and can be imported into most IDEs?  I recall loading one into
NetBeans years ago.  This is separate from Checkstyle; it configures
the IDE to follow our rules in its own auto-formatting, so you don't
make Checkstyle unhappy in the first place.

-- 
Mark H. Wood
Lead Technology Analyst

University Library
Indiana University - Purdue University Indianapolis
755 W. Michigan Street
Indianapolis, IN 46202
317-274-0749
www.ulib.iupui.edu

2023-05-02 15:58 UTC, tdonohue commented
@mwoodiupui : Yes, our `checkstyle.xml` config file is what can be imported into every IDE, provided that you have the IDE-specific "checkstyle plugin".  I believe every Java IDE supports checkstyle, but some may require you to install a plugin. Again, though, the instructions for most IDEs are in our Code Style Guide:  https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide#CodeStyleGuide-IDESupport

2023-05-03 07:09 UTC, Ma-Tador commented
Thank you @tdonohue and @mwoodiupui. I will migrate to IntelliJ since so many developers here use it and I will set the checkstyle as instructed. Thank you for sharing.
I changed the <code>RegistrationRestRepositoryIT</code> as instructed.

2023-05-03 15:52 UTC, tdonohue approved these changes
👍 Thanks @Ma-Tador !  This looks correct now.  Already tested the code and found it to be working.

2023-05-03 15:52 UTC, merged