#8636 Request a Copy's "helpdesk" strategy requires authentication t…
DSpace/DSpace pull request #8795
Opened 2023-04-20 09:23 UTC by aroman-arvo

## References
* Fixes #8636
* Related to DSpace/RestContract#`pr-number`

## Description
Allow grant access without authentication

## Instructions for Reviewers
List of changes in this PR:
* Bitstream can be added to grant email without authorized logged user.

To test:

1.  Activate request a copy with Helpdesk Strategy: https://wiki.lyrasis.org/display/DSDOC7x/Request+a+Copy#RequestaCopy-(Optional)RequestingacopywithHelpDeskworkflow
2. As anonymous user, look at an embargoed item, click on the file to display the request a copy form.
3. Complete and send the request a copy form
4. As helpdesk staff, look at the email inbox
5. Open the Request a copy email and click on the link to respond to it.
6. Approve  the request (without login)
7. 
## Checklist

- [X] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [X] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [X] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [X] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [X] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [X] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [X] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [X] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

2023-05-05 19:21 UTC, tdonohue requested changes
@aroman-arvo : I finally got to reviewing & testing this today.  This ALMOST works, but it still throws an exception (on the backend) if the user submits the request for "All files"
![all-files](https://user-images.githubusercontent.com/483997/236550652-77b20463-bea0-4be9-945a-5e182d51e931.png)

The reason it still fails is that you've only added the `turnOffAuthorizationSystem()` lines in the `else` portion of a larger if statement.  Those lines also need to be added around line 170-171, where all files are added as attachments.

I have verified though that this code works and looks good.  You just need to surround line 170-171 with the same changes that you have applied later.

2023-05-08 19:58 UTC, tdonohue requested changes
@aroman-arvo :  After retesting today, I've realized that this PR along with the corresponding frontend PR (https://github.com/DSpace/dspace-angular/pull/2199) **accidentally introduces a security vulnerability**.

**With these two PRs in place, it's possible to approve your own requests for copy.** The flaw is not entirely the fault of this PR though...part of the issue is how "Request a Copy" currently works.  But, it is ONLY exploitable with these two PRs installed & is not possible to exploit on `main` or in 7.5.

Here's how to do it:
1. First, open the User Interface as an anonymous user (not logged in)
2. Now, open up your browser's DevTools (Network Tab) so that you see every request/response to/from the REST API.
3. Browse to an Item with a restricted bitstream.
4. Submit a Request for a copy of that bitstream.
5. In your DevTools (Network Tab) you'll be able to see the `/itemrequests` call made the REST API.  If you look at the response to that request, you can find the random `token` returned for that copy request.
6. Using the random token, now visit `http://localhost:4000/request-a-copy/{token}` in your browser.  
7. You will be able to now approve your own request and send yourself the restricted documents.

On `main`. or 7.5, you cannot achieve the same thing because you will be blocked on step 6 or 7.
* If you are not logged in and try to visit `http://localhost:4000/request-a-copy/{token}`, you will be prompted to login.
* If you register for an account & login, you *will be able* to visit `http://localhost:4000/request-a-copy/{token}`... but if you try to submit the form, you will receive a 500 exception because of the Bitstream authorization checks in the code.

I think the only way to fix this may require refactoring how Request a Copy works.  It should NEVER send the random `token` back to the User Interface / Client.  Instead, that token should only be sent via email (so that it is never seen by the client).  

Pinging @mwoodiupui  on this discussion as well, since I know he was involved in the initial design of this feature.  I think we have a general flaw in that original design, but we are protected currently by the authorization/authentication checks which these two PRs now remove.

2023-05-09 12:57 UTC, mwoodiupui commented
I agree:  the requestor has no business ever seeing the token, which is meant solely for the person(s) who will grant or deny the request.

2023-05-09 15:33 UTC, tdonohue commented
@mwoodiupui or @aroman-arvo : Would one of you be willing to change the `POST /api/tools/itemrequests` to return a 201 with an **empty body**? Currently it returns a JSON response as documented here: https://github.com/DSpace/RestContract/blob/main/item-requests.md#creating-a-request

If that change is made, then this PR _would be acceptable as-is_.  However, we cannot move this PR forward until that change is made.  That change could be made within this PR, or it could be done as a separate PR.

I feel this fix an important change to make for 7.6 if possible.  If neither of you have time, I'll see if I can find time to make the change.  The current behavior is very obviously flawed & should be fixed as soon as possible.

2023-05-16 14:07 UTC, aroman-arvo commented
I think its OK now

2023-05-16 14:23 UTC, tdonohue commented
Thanks @aroman-arvo .  I'll give this a fresh review now and see if it looks good

2023-05-16 19:06 UTC, tdonohue reviewed
@aroman-arvo :  Thanks!  The latest changes fix the security issue!   I have a few recommendations to improve your Integration Tests (to block against someone accidentally reintroducing the security issue & also to delete any created requests).  Once those are made, I'm +1 this PR.

2023-05-17 21:46 UTC, tdonohue approved these changes
👍 Thanks @aroman-arvo !  This works and it looks good to me.  The potential security issue has been patched and the behavior of Request a Copy is improved!

2023-05-17 21:46 UTC, merged