Primary bitstream support for the REST api
DSpace/DSpace pull request #8798
Opened 2023-04-20 13:30 UTC by KevinVdV

## References
* Fixes #3349

## Description

Rest changes according to the following contract: https://github.com/DSpace/RestContract/pull/222

## Instructions for Reviewers

Take a look at the changes in the contract & try them on the branch.

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [X] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [X] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [X] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [X] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [X] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [X] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [X] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [X] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

2023-05-07 13:10 UTC, abollini requested changes
thanks for this contribution @KevinVdV I have tried to give direction inline to update this PR according to the suggestions in https://github.com/DSpace/DSpace/pull/8798

2023-05-07 13:10 UTC, abollini commented on dspace-api/src/test/java/org/dspace/builder/BundleBuilder.java
> +
would be better to add an overloaded method `addBitstream` that takes a second parameter `boolean isPrimary` used to set the primary bitstream in the bundle?
in this way the api should look easier to use and there is no risk that someone would set a primary bitstream that is outside the bundle

2023-05-07 13:10 UTC, abollini commented on dspace-server-webapp/src/main/java/org/dspace/app/rest/model/BundleRest.java
changes to this class are not required if we implement the REST API according to our general rules using the text/uri-list support

2023-05-07 13:10 UTC, abollini commented on dspace-server-webapp/src/main/java/org/dspace/app/rest/converter/BundleConverter.java
changes to this class are not required if we implement the REST API according to our general rules using the text/uri-list support

2023-05-07 13:10 UTC, abollini commented on dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/patch/operation/BundlePrimaryBitstreamUUIDAddOperation.java
this logic should go in a dedicated controller similar to `org.dspace.app.rest.ItemOwningCollectionUpdateRestController`

2023-05-07 13:10 UTC, abollini commented on dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/patch/operation/BundlePrimaryBitstreamUUIDRemoveOperation.java
this logic should go in a dedicated controller similar to `org.dspace.app.rest.ItemOwningCollectionUpdateRestController`

2023-05-07 13:10 UTC, abollini commented on dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/patch/operation/BundlePrimaryBitstreamUUIDReplaceOperation.java
this logic should go in a dedicated controller similar to `org.dspace.app.rest.ItemOwningCollectionUpdateRestController`

2023-05-12 16:57 UTC, tdonohue requested changes
@KevinVdV : Similar to @abollini , I feel this design doesn't align well with our existing REST API guidelines.  PATCH doesn't seem appropriate, and we should be using PUT instead to create the "primary bitstream" relationship between a Bundle and a Bitstream.  See my review of the contract for details: https://github.com/DSpace/RestContract/pull/222#pullrequestreview-1424862089

If this PR can be refactored to use that approach, that would be best.

2023-05-22 15:24 UTC, tdonohue commented
@KevinVdV and @benbosman : Friendly reminder that the Primary Bitstream work (all PRs) needs updating.  This has been sitting for 10 days now, and we'd need it to move more quickly if we are going to have time to review/approve it for 7.6.  Review deadline is this coming Friday (May 26). Merge deadline is June 9.  Thanks!

2023-06-01 20:18 UTC, tdonohue commented
Closing, replaced by #8876

2023-06-01 20:18 UTC, closed without merging