Fix validation issue with hidden submission's sections
DSpace/DSpace pull request #8842
Opened 2023-05-11 16:55 UTC by atarix83

## References
* Fixes https://github.com/DSpace/dspace-angular/issues/2169

## Description
With this PR the submission's sections that are hidden for the specific submission scope (workspace/workflow) are no longer returned into the submission process so they are not taken into account during the validation process.

## Instructions for Reviewers
Follow instructions present in the https://github.com/DSpace/dspace-angular/issues/2169 and check that is fixed

List of changes in this PR:
* The submission's sections that are hidden for the current scope are not returned in the submission object
* The submission's sections are validated only if visible for the scope

## Checklist
- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [x] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

2023-05-31 20:34 UTC, tdonohue requested changes
@atarix83 : Thanks! This looks good overall and I've verified that it fixes the originally reported bug.  So, I'm nearly a +1.

However, I have a few minor  requests for missing Javadoc and also a (possibly) missing integration test.  Beyond that though, this looks good and works.

2023-06-01 12:49 UTC, atarix83 commented on dspace-server-webapp/src/test/java/org/dspace/app/rest/WorkspaceItemRestRepositoryIT.java
> +            .andExpect(jsonPath("$.sections.test-always-hidden").doesNotExist());
done

2023-06-01 12:49 UTC, atarix83 commented on dspace-api/src/main/java/org/dspace/app/util/SubmissionStepConfig.java
> +    public boolean isHiddenForInProgressSubmission(InProgressSubmission obj) {
done

2023-06-01 15:55 UTC, tdonohue approved these changes
👍 Thanks @atarix83 !  This looks correct to me now and works.  As soon as it completes it's automated tests / CI process, I'll merge it.

2023-06-01 16:31 UTC, merged