Sort for BrowseIndex with "text" datatype but use "date" sort option
DSpace/DSpace pull request #8871
Opened 2023-05-29 01:46 UTC by buithaihai

## References
Fix [8651](https://github.com/DSpace/DSpace/issues/8651)
Fix (clarify) [8646](https://github.com/DSpace/DSpace/issues/8646)

## Description

This PR slightly changes how `BrowseIndex.getDataType()` works, which now accounts for when`webui.browse.index.<X>` uses a sort option that is not of the same data type as the BrowseIndex's own data type by prioritizing the BrowseIndex's. Some other changes also need to be made to follow suit.

In addition, we add some comments in `dspace.cfg` to clarify the limitations of `webui.itemlist.sort-option._`

This PR does not fix the ds-angular bug which does not respect the default sort order from `/server/api/discover/browses`.

## Instructions for Reviewers

### List of changes in this PR:
1. Updated `BrowseIndex.getDataType()`
2. Changed `org/dspace/browse/BrowseEngine.java:223` so that now it has to use explicit `scope.getBrowseIndex().getSortOption().getType()` if possible:
```java
                value = OrderFormat.makeSortString(value, scope.getFilterValueLang(),
                                                   scope.getBrowseIndex().getSortOption() == null ?
                                                           scope.getBrowseIndex().getDataType() :
                                                           scope.getBrowseIndex().getSortOption().getType());
```
3. Use `bi.getSortOption().getNumber()` if available when we do second level search (check code change for context & details, this is hard to explain properly here).
### For Testing:
1. Added the following test case:
- `org.dspace.app.rest.BrowsesResourceControllerIT#testBrowseAuthorByEntriesSortByDateIssued`:  verify that with configuration `webui.browse.index.2 = author:metadata:dc.contributor.*\,dc.creator:text:desc:dateissued`, we can get a list of entries and a list of items sorted by `dateissued` with filtered value "Universe2"

2. Testing on a working system:
a. In `dspace.cfg`, change the following config as such:
```
webui.browse.index.2 = author:metadata:dc.contributor.*\,dc.creator:text:desc:dateissued
```
b. On dspace-angular, check Top Navigation bar -> menu **"All of DSpace"** (Browse by) -> **"By Author"**
 - The list of authors should be shown
 - Click on an author should show a list of their items, sorted by `dc.dateissued`, in descending order

## Checklist
- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [x] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

2023-05-29 12:03 UTC, buithaihai commented
## Extra note
It seems like we have gone as far as the "Browse" feature permits. To continue improving "Browse" further is like a fool's errand at this point and since a proposal for a replacement with Discovery has been raised, we (DLCorp) would like to express our interest in it and to claim it in the future, should it not be claimed by other parties.

2023-06-13 21:35 UTC, tdonohue requested changes
@buithaihai : I tried testing this today, but it is breaking the "Browse by Author" and "Browse by Subject" in the current Angular UI.  So, it's not functional as-is.

Here's how to reproduce the issue:
1. Installed this PR on the backend and deployed.  I've kept my browse configuration to use the default settings in `dspace.cfg`: https://github.com/DSpace/DSpace/blob/main/dspace/config/dspace.cfg#L1140-L1143
3. Deployed latest frontend (`main`) branch, running in production mode (`yarn build:prod; yarn serve:ssr`)
4. Go to "Browse by Subject".  Click on any subject.  The page will not load.  Here's a screenshot of what it looks like:
![browse-by-subject-never-loads](https://github.com/DSpace/DSpace/assets/483997/133e750d-2184-46ab-8a4c-3190e8bee11f)
5. The same behavior also exists with "Browse by Author".  Click on any author and the page will not load.  (Browse by Title/Date work properly however)

In my browser's DevTools Console, I see this error:
```
ERROR TypeError: Cannot read properties of undefined (reading 'href')
    at main.aa20f532260f4d65.js:1:200299
    at main.aa20f532260f4d65.js:1:1677509
    at i._next (main.aa20f532260f4d65.js:1:1673529)
    at i.next (main.aa20f532260f4d65.js:1:1662321)
    at main.aa20f532260f4d65.js:1:1676238
    at i._next (main.aa20f532260f4d65.js:1:1673529)
    at i.next (main.aa20f532260f4d65.js:1:1662321)
    at main.aa20f532260f4d65.js:1:1677502
    at i._next (main.aa20f532260f4d65.js:1:1673529)
    at i.next (main.aa20f532260f4d65.js:1:1662321)
```

It appears to possibly be referencing this line of code? https://github.com/DSpace/dspace-angular/blob/main/src/app/core/browse/browse.service.ts#L124

Overall, the concepts in this PR seem reasonable.  But, it appears more work is needed to either align the UI code with the changes here... or provide a behavior out of this PR which doesn't break the UI.

2023-06-14 09:53 UTC, buithaihai commented
This is part of the fix for #8879, however, it was not working since I removed the `/items` endpoint for `valueList` as suggested here:

> * The reason is that the "author" browse is a `valueList` and a `valueList` doesn't support `/items`

It is actually used, just not the way that is giving 500. It is actually used like this:

`http://192.168.1.179:8080/server/api/discover/browses/author/items?filterValue=<value>`

So the proposed course of action was actually wrong, reinstating the support fixes it. This means that we cannot fix the 500 error for type `valueList`, however.

**NOTE**: In addition, I also remove both `/items` and `/entries` for `hierarchicalBrowse` type since they are producing 500 error on these endpoints, mainly because this type of browse is not configured by `webui.itemlist.sort-option.*` in _dspace.cfg_.

2023-06-14 21:28 UTC, tdonohue requested changes
@buithaihai : Re-tested today, and those issues with Browse by Subject & Browse by Author are gone.

However, now I'm seeing this error in my DevTools Console for "Browse by Title":
```
ERROR TypeError: Cannot read properties of undefined (reading 'href')
    at main.ec53954ff112466a.js:1:199687
    at main.ec53954ff112466a.js:1:1679401
    at i._next (main.ec53954ff112466a.js:1:1675421)
    at i.next (main.ec53954ff112466a.js:1:1664219)
    at main.ec53954ff112466a.js:1:1678130
    at i._next (main.ec53954ff112466a.js:1:1675421)
    at i.next (main.ec53954ff112466a.js:1:1664219)
    at main.ec53954ff112466a.js:1:1679394
    at i._next (main.ec53954ff112466a.js:1:1675421)
    at i.next (main.ec53954ff112466a.js:1:1664219)
```

How to reproduce:
1. Install this PR. Run in production mode
2. Open your browse DevTools...keep an eye on the console.
3. Visit "Browse by Title".  The error will appear.

This error doesn't appear to break Browse by Title functionality, but it implies to me that maybe we don't have a good idea yet of how to truly fix #8879.

I'm worried this PR is trying to do too much at this point.  I'd recommend **removing any fixes** related to #8879.  I think those will need more analysis to fix the 500 errors *without* causing a new `TypeError: Cannot read properties of undefined (reading 'href')` in Angular.   I think that analysis may take more time, and isn't likely to be ready for 7.6.

Beyond that, the rest of this PR appears to be working.  It's just that the strategy for fixing #8879 seems to not be correct.

2023-06-15 00:29 UTC, buithaihai commented
I think that the fix still works, just that angular code really needs to accommodate the changes. I will be reverting the code for now and see if I can revisit this fix in the future.

2023-06-15 21:26 UTC, tdonohue requested changes
@buithaihai  : Sorry, I'm still having issues with getting this PR to work with the Angular UI.  I suspect the reason may be, as you noted, that we may need a corresponding Angular UI PR to fully fix these bugs.

Today, I installed this PR, reindexed (`./dspace index-discovery -b`) and tried to reproduce the bug described in #8651 (by following the "To Reproduce" steps in that PR's description).  **That bug still exists even with this PR installed.**  
* The Browse by Issue Date in the user interface still sorts (wrongly) by ASC instead of DESC
* The Browse by Author in the user interface still results in an error in the backend logs (dspace.log) and its sort also doesn't appear to be changed?

I do think the code in this PR is a step in the right direction... but I suspect we need to figure out what changes are required in the User Interface before we can move this forward, as it doesn't appear to fix the initially reported bug.

So, I don't see a good reason to merge this for 7.6 right now as it doesn't appear to change the UI behavior.  We either need to find a fix that changes the UI behavior, or consider even
replacing the "Browse by" logic with Discovery at some point soon, since these problems seem specific to the old "Browse by" code.  But full replacement is obviously a large project.

Another comment inline below about the fix for #8646.  I think the comments are slightly wrong, unless I am misunderstanding what you mean.

Overall, the direction here seems good... I just don't know how to move it forward until we find a way to get it to work with the User Interface.

2023-06-15 23:00 UTC, buithaihai commented
I think delaying this PR for later is fine. I will try to implement the necessary angular changes.

2023-06-22 05:57 UTC, buithaihai commented on dspace/config/dspace.cfg
> +#       (mydspace, workflow, etc) please check out spring/api/discovery.xml
I have been trying to explain this in a good way but failed. What I mean is that the equivalent of these `webui.itemlist.sort-option.*` is the `searchSortConfiguration` property that can be found in **discovery.xml**. Therefore if someone wants to change sort options in, like "_My DSpace_", they should go to `searchSortConfiguration` of `bean id="workspaceConfiguration"`.

2024-05-14 14:38 UTC, tdonohue commented
Closing as this has not been worked on in over a year and is outdated.  We can reopen later if need be.

2024-05-14 14:38 UTC, closed without merging