Updated bitstream patch validation
DSpace/DSpace pull request #9206
Opened 2023-11-16 20:15 UTC by mspalti

## Description
Earlier this week I noticed although that I could [modify UploadConfiguration](https://wiki.lyrasis.org/display/DSDOC7x/Submission+User+Interface#SubmissionUserInterface-ModifyingmetadataformpresentedforBitstreams) for the UI, it's not possible to use a custom metadata submission form for `bitstreams.` You can create a new `UploadConfiguration` bean with a custom metadata form and add this to the `UploadConfigurationService` bean in `access-conditions.xml` (as described in the documentation). This can be mapped to a submission process by handle and the metadata form appears in the UI. But when you submit the changes to the backend the PATCH operation fails.

This is because the backend is hard-coded to use the default "bitstream-metadata" form in `submission-forms.xml` for validation. In fairness, this seems consistent with the documentation. 

The changes in this PR allows for custom bitstream metadata forms in addition to the default "bitstream-metadata" form. 

## Instructions for Reviewers
List of changes in this PR:
* Patch validation changed to use the UploadConfigurationService to read the metadata used for validation.

I believe current IT's provide test coverage.

Testing requires a submission configuration that uses an alternative bitstream metadata form. I suppose it's possible to define the new form in `submission-forms.xml` and then just use this form
name in the  `uploadConfigurationDefault` "metadata" property. A more complete and realistic test is to create a new submission process, but that's probably not necessary for testing.

Question: The dc.title field is required so it seems like we could add a check for the required title field during validation. I wanted to see what others think first.

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [ ] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [ ] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [ ] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [ ] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

2024-02-29 15:30 UTC, abollini requested changes
Hi @mspalti  I figured out that we solved the same issue in DSpace-CRIS some time ago, it should be ok to backport our solution to dspace but I'm not sure if tests where added or need to be written. If you are interested in that I would suggest to look here: https://github.com/4Science/DSpace/blob/main-cris/dspace-server-webapp/src/main/java/org/dspace/app/rest/utils/BitstreamMetadataValuePathUtils.java#L45 retrieving the involved commits

2024-03-02 01:09 UTC, mspalti commented
Thanks @abollini. I will take a look at the DSpace-CRIS code.

Just wondering, did you also work on the bitstream edit form for existing bitstreams (under Item edit)? I've had time recently to modify it to use the bitstream form that is configured for the collection and might have a working proposal soon. If this has already been done by someone else who can share that would be great!  The dynamic forms are tricky. (It's mostly Angular with possibly a minor REST addition).

2024-03-26 22:59 UTC, mspalti commented
Hi @abollini , sorry for the delay. I ported your dspace-cris code and tested locally. It works as expected. I didn't notice any ITs that cover this feature. Presumably, if they do exist they prove that the change didn't break anything.

2024-05-14 14:52 UTC, tdonohue approved these changes
👍 Thanks @mspalti !  I've verified this code works as described.  I was able to create a custom Bitstream `<form>` in `submission-forms.xml` named `advanced-bitstream-metadata`, adding some new metadata fields.  Then, I was able to use that form by changing the `uploadConfigurationDefault` bean in my `access-conditions.xml` to have a `metadata` property of `advanced-bitstream-metadata`.

2024-05-14 14:52 UTC, tdonohue commented
I've also verified the previously failing ITs in this PR were already fixed on `main`.  They are unrelated to this PR.

2024-05-14 14:52 UTC, merged