captcha on request copy
DSpace/DSpace pull request #9235
Opened 2023-12-18 05:38 UTC by GauravD2t

## References
_Add references/links to any related issues or PRs. These may include:_
* Fixes #https://github.com/DSpace/DSpace/issues/8976

## Description
 requestCopy.verification.enabled=true/false in the configuration file

## Instructions for Reviewers
Please add a more detailed description of the changes made by your PR. At a minimum, providing a bulleted list of changes in your PR is helpful to reviewers.

List of changes in this PR:
* First, ...
* Second, ...

**Include guidance for how to test or review your PR.** This may include: steps to reproduce a bug, screenshots or description of a new feature, or reasons behind specific changes. 

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [x] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

2024-01-22 20:07 UTC, paulo-graca commented on dspace/config/dspace.cfg
> +#---------------------------------------------------------------#
could you consider to add a new modules/google-captcha.cfg file? I think there are several configurations for Google Captcha. Perhaps it already deserves a single configuration file for it.

And also add a reference for it on `dspace.cfg`:
```
include = ${module_dir}/google-captcha.cfg
```

2024-01-31 17:55 UTC, tdonohue requested changes
@GauravD2t : I reviewed/tested this today alongside the frontend PR.  See more details in [my review of that PR](https://github.com/DSpace/dspace-angular/pull/2712#pullrequestreview-1854345937)

I have some additional suggestions in this PR... see inline below.

2024-03-04 22:44 UTC, tdonohue commented
@GauravD2t : Unfortunately this feature missed our feature merger deadlines for 8.0 (as feedback was not addressed in time).  It will need to be rescheduled for 9.0.

2026-02-07 19:45 UTC, bram-atmire commented
Closing this PR which missed the DSpace 8.0 deadline and has been stalled since March 2024. @tdonohue requested changes in January 2024 that were never addressed, and the author has been inactive for nearly 2 years. The PR has merge conflicts.

The captcha-on-request-copy feature could be re-implemented by an active contributor if still needed. Thank you @GauravD2t.

2026-02-07 19:45 UTC, closed without merging