Enforce resource policies to have group or eperson (DSpace 8)
DSpace/DSpace pull request #9502
Opened 2024-04-25 09:56 UTC by YanaDePauw

## References
* Fixes #9190 
* DSpace 8 version of #9191

## Description
The DSpace code currently does not enforce that a created resource policy has either a connected group or eperson.
As a consequence, it can happen that a resource policy is created with neither.

This will then cause issues down the line where DSpace assumes that all resource policies have either a group or eperson connected to it.

## Instructions for Reviewers
Verify that it is no longer possible to create a resource policy without a group or eperson. 

## Checklist
- [ ] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [x] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

2024-04-29 17:28 UTC, tdonohue requested changes
@YanaDePauw :  Gave this a look & test today.  Overall, the code changes look good.  However, the DB migration is failing because the Constraint cannot be added until we *first* delete all rows which fail that constraint.  See inline comment below.

Once this migration is fixed, I can perform a more thorough test.  (The migration also will need to be fixed in the 7.x version of this PR too)

2024-04-29 17:28 UTC, tdonohue commented on dspace-api/src/main/resources/org/dspace/storage/rdbms/sqlmigration/postgres/V7.6_2023.09.28__enforce_group_or_eperson_for_resourcepolicy.sql
> +DELETE FROM ResourcePolicy WHERE eperson_id is null and epersongroup_id is null;
@YanaDePauw :  I think the DELETE needs to come *BEFORE* the Constraint is added.  I tried testing this by adding in a few ResourcePolicy rows that have a null `eperson_id` and `epersongroup_id` and I get this error when the Constraint is added:

```
ALTER TABLE ResourcePolicy ADD CONSTRAINT resourcepolicy_eperson_and_epersongroup_not_nullobject_chk
    CHECK (eperson_id is not null or epersongroup_id is not null)

        at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.handleException(DefaultSqlScriptExecutor.java:252)
        at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:214)
        at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.execute(DefaultSqlScriptExecutor.java:133)
        at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.executeOnce(SqlMigrationExecutor.java:65)
        at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.lambda$execute$0(SqlMigrationExecutor.java:57)
        at org.flywaydb.core.internal.database.DefaultExecutionStrategy.execute(DefaultExecutionStrategy.java:27)
        at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.execute(SqlMigrationExecutor.java:56)
        at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:374)
        ... 26 more
Caused by: org.postgresql.util.PSQLException: ERROR: check constraint "resourcepolicy_eperson_and_epersongroup_not_nullobject_chk" of relation "resourcepolicy" is violated by some row
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2725)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2412)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:371)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:502)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:419)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:341)
        at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:326)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:302)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:297)
        at org.apache.commons.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:182)
        at org.apache.commons.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:182)
        at org.flywaydb.core.internal.jdbc.JdbcTemplate.executeStatement(JdbcTemplate.java:210)
        at org.flywaydb.core.internal.sqlscript.ParsedSqlStatement.execute(ParsedSqlStatement.java:89)
        at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:206)
```

2024-04-30 17:07 UTC, tdonohue approved these changes
👍 Thanks @YanaDePauw !  I've verified this is now working properly and the migration accurately removes any invalid policies (ones with no group and no eperson).  Code all looks good and I'm not finding any issues when testing the backend with the frontend.

2024-05-02 09:07 UTC, YanaDePauw commented
@tdonohue I think I may have done the merging in reverse. I have done a remerge and force pushed that version. I believe this should solve the issues

2024-05-02 18:00 UTC, tdonohue commented
@YanaDePauw : I'm not exactly sure what is going on with this PR, but it's still showing 395 commits ... instead of the 10 that are shown in your other PR #9191.   (As a sidenote, the PR#9191 has a small merge conflict that needs solving too)

It seems like somehow this branch has been messed up in a way that is confusing GitHub.  Maybe it'd be worth starting a new branch from `main` and simply cherry-picking the 10 commits to that branch?  That'd require creating a new PR though.

2024-05-03 08:41 UTC, YanaDePauw commented
Perhaps there is some discrepancy between the 7.6 version and the 8.0 version, which causes the extra commits. Ill look into cherry-picking the changes on a clean dspace 8.0 branch

2024-05-03 14:42 UTC, tdonohue commented
Thanks @YanaDePauw !  That latest force push seems to have fixed things in this PR.  I'll give it one last test (to verify no behavior changes) and then get this merged.

2024-05-03 15:11 UTC, tdonohue approved these changes
👍 Thanks @YanaDePauw !  Verified this is still working properly after the commit cleanup.

2024-05-03 15:15 UTC, merged