Duplicate data from an existing Item to a new WorskpaceItem, aka clone/copy item
DSpace/DSpace pull request #9608
Opened 2024-05-24 17:39 UTC by MMilosz

## References
* Fixes DSpace/dspace-angular#1757
* Angular PR DSpace/DSpace-angular#3076

## Description
This PR introduces the ability to create a new WorkspaceItem by reusing properties from an existing Item, kind of like how versioning works now, but resulting in a partially completed edit form of a new Item. Some existing code from the versioning infrastructure was adapted and integrated as two new methods, `copy` and `clone`, within the ItemService, and tweaked, just to make things work more smoothly.

Here's a preview:

https://github.com/DSpace/dspace-angular/assets/17811486/ad5f70b1-f14f-49d2-884c-63fb906fd642

## Instructions for Reviewers

On the REST side:

Example request (endpoint, header, body):
```
POST /api/submission/workspaceitems?owningCollection=:collectionUuid
Content-Type: text/uri-list

http://localhost:8080/server/api/core/items/:itemUuid
```

Response should show a new WorkspaceItem with some of the metadata copied from the specified :itemUuid. Although some of the metadata **will be omitted** to prevent duplicates or multiple values in places they shouldn't occur – see `nonCopyableMetadataFields` in `core-services.xml`.

On the Angular side:

* Login as admin and either deposit a new item or locate an existing one.
* Navigate to the _item management page_ (edit -> status).
* Between _move_ and _delete_, a new button should be visible for _cloning_ the item. Click it, select any collection, then click _save_.
* The browser should redirect the user to the edit form, similar to what happens after creating a new item. However, most of the metadata should be copied from the previous item.

## Checklist
- [X] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [X] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [X] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [ ] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [X] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [ ] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [X] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [X] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

2024-08-28 13:59 UTC, kshepherd requested changes
Hi @MMilosz , thanks for the new feature. I've tried it out and it is working well.

Just two things:

1. The changes make sense in general (the new clone / copy methods and the refactoring of some copying in version providers), but I think there might be something missed when replacing the copyMetadata method + calls in the version providers, hence the failing integration tests...

Could you check to make sure `VersionProvider#updateItemState` definitely still does what it did before?

(if there is a different reason for these ITs to be failing, please let me know - I restarted the job today and it still failed, and isn't failing for other recent PRs so I figured there probably is some downstream impact from the change)

2. The very first time I cloned an item, I got the "success" notification and just stayed on the item page. The cloned item was created in my workspace as expected, once I went to My DSpace, but in all my other tests the clone action also directed me to the form for the new workspace item. I couldn't reproduce this afterwards, but I wanted to note it here.

2024-08-28 14:48 UTC, MMilosz commented
Hello @kshepherd, thanks for the feedback. I'm glad to read the feature is working well overall.

Since I've got your attention, do you agree with the direction I've taken regarding the REST operation or do you have any thoughts on a different approach? I'm still toing and froing whether the clone operation:

1. should be handled as it is in my PR (vide: `ExternalSourceEntryItemUriListHandler`)?
2. the distinction between `ItemService#clone` (to create a new Item) and `ItemService#copy` (void; to copy data from one Item to another) – isn't a bit confusing?

I'll have a look into the ITs and mention you again after checking what's happening inside a `VersionProvider#updateItemState`.

2024-09-01 11:12 UTC, kshepherd commented
@MMilosz regarding the approach / code:

I think `clone` is an OK service method name, and `copy` or `deepCopy` make sense to me, especially when viewed with their return types, it is clear that copy wants an existing object as a target (returning void) while clone is going to return a new Item.

I think the changes / use of ExternalSourceEntry* endpoints can cause a bit of confusion, though it's not your fault that `ExternalSourceEntryItemUriListHandler<T>` is the base handler for anything of type workpace item... perhaps we could abstract this, or even just rename the classes to something more generic like `WorkspaceItemUriListHandler<T>`, and make it more clear in javadoc, comments and the structure of the logic there, that the URI lists can contain hrefs to external data object entries, *or* existing DSpace objects.

(In general though, I support the idea of using the existing 'createAndReturn with uri-list' paradigm since it is how we do things for similar cases, and existing items in dspace which we want to use as the source, are addressable objects with URIs...)

With changes to core behaviour like how the versioning provider operates, we just have to make sure we really nail down what it means to "copy" an item, how we test that, and how we ensure things continue to work as before.
A new equality operator for Item, to go along with the `copy()` and `clone()` methods might be useful for more thorough tests - eg. `isCloneOf()` or something.

2024-09-26 09:36 UTC, kshepherd commented
@MMilosz if the current IT failures seem spurious, try rebasing against main and force pushing your branch again, just in case it is not related to your changes.

When there are new commits/changes ready for a re-review or feedback please let me know, and a brief explanation of the latest changes would help

2025-01-29 15:30 UTC, kshepherd commented
@MMilosz could you please rebase against main and force push? (or if you're happy for me to do it, i can do this myself)

2025-03-13 15:09 UTC, steph-ieffam reviewed
Hey @MMilosz 
I checked your PR and the feature is working fine but I have some concerns about the usage of the DSpace External Data framework to clone an item.
The external data framework should be used in my opinion just to create Workspace items starting from a real external source.
For this purpose the usage of the Item's related endpoints seems more correct.
Moreover there's an overlapping with existing DSpace CRIS feature for the Request a correction feature. It's a different feature but the base of the feature is cloning an item and related metadata starting from an item (considered as source)

As an additional note I don't really get the point of cloning items in this way, but as long as there are institutions requesting for this feature my opinion doesn't really matter, even thought I find more appropriate the Versioning feature.

CC: @tdonohue

2025-03-17 15:21 UTC, tdonohue requested changes
@MMilosz : I gave this a quick code review today.  Overall, the code looks reasonable, but it seems to have some unforeseen bugs (which may be why the Integration Tests are still failing).  I think the code also needs more automated tests to ensure it truly is working properly.

Finally, I did want to note that I've recently realized that this feature exists in DSpace-CRIS in a slightly different form.  Because of that, we're unfortunately going to have to temporarily delay this feature because DSpace Steering asked us to not add new features would may "conflict with" or "complicate" a [potential merger with DSpace-CRIS](https://dspace.org/dspace-and-dspace-cris-intent-to-investigate-merger-announcement/) in the future.  While the potential merger is still under discussion, the 9.0 release is not supposed to add any conflicting features.

I've gone ahead and left my initial feedback on this PR.  However, I'm going to pull this over into our "on hold" column on the current project board.  We unfortunately cannot add this to 9.0, but we can revisit it later on as the potential merger discussions progress to determine if it's possible to add to a later release.

2025-03-17 15:21 UTC, tdonohue commented on dspace-api/src/test/java/org/dspace/content/ItemTest.java
> +    }
We need more tests here for all the copy/clone actions that you've defined. We should be testing that clone is moving the item to a new collection when specified. We should be testing that clone is copying all existing metadata fields from the source to the target, copying the expected bundles/bitstreams and expected resource policies.

2025-03-17 15:21 UTC, tdonohue commented on dspace/config/spring/api/core-services.xml
> +                <value>dspace.entity.type</value>
This field arguably *should* be copied, as you'd want to ensure an existing Entity is copied into the same type of object (e.g. you wouldn't want to copy a Person Entity into a plain Item).

2025-03-17 15:21 UTC, tdonohue commented on dspace/config/spring/api/core-services.xml
> +                <value>dc.provenance</value>
This field doesn't exist in DSpace out-of-the-box. So it shouldn't be listed here.

2026-02-07 19:45 UTC, bram-atmire commented
Closing as @tdonohue explicitly put this on hold in March 2025 due to the DSpace-CRIS merger: "We unfortunately cannot add this to 9.0." Similar clone/copy functionality already exists in DSpace-CRIS, and merging this separately could create conflicts with the CRIS integration.

This can be revisited after the CRIS merger discussions conclude. Thank you @MMilosz for the implementation work.

2026-02-07 19:45 UTC, closed without merging