fix: `replace` PATCH request on /metadata now supports multiple values
DSpace/DSpace pull request #9610
Opened 2024-05-27 07:34 UTC by MMilosz

## References
* Fixes DSpace/dspace-angular#2056
* Is required by DSpace/dspace-angular#3078

## Description
This PR adds a support for arrays in the existing `replace` PATCH operations. 

## Instructions for Reviewers

Before:
WIP

After:
WIP

## Checklist
- [X] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [X] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [X] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [X] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [X] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [ ] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [X] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [X] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

2025-02-06 13:33 UTC, artlowel approved these changes
Thanks @MMilosz!

I've verified that this works by testing https://github.com/DSpace/dspace-angular/pull/3078 using this as a backend.

It would be good if someone else could do a code review though, as I don't write a lot of Java these days

2025-02-06 16:33 UTC, tdonohue commented
@MMilosz : As you know, we discussed this in today's Developers Meeting.  The primary feedback was around whether the `replace` operation should be used for this PATCH, or if the `add` operation is more appropriate.  

As documented in our REST Contract, [for the `add` operation](https://github.com/DSpace/RestContract/blob/main/metadata-patch.md#adding-metadata):
> You also use add to effectively _replace_ all values for a given metadata key, by specifying an already-present key as the path, and an array of your replacement values as the value. This use of the add operation to replace a list of values may be counter-intuitive, but it is done according to the [RFC section 4.1](https://tools.ietf.org/html/rfc6902#section-4.1)

So, per that discussion, we recommended seeing if the `add` operation already supports what you are trying to do.  The `replace` operation is expected to always target an individual value [per RFC Section 4.3](https://datatracker.ietf.org/doc/html/rfc6902#section-4.3)

This does mean though that our documentation for `replace` appears to be wrong at https://github.com/DSpace/RestContract/blob/main/metadata-patch.md#replacing-metadata   We should be telling people to use `add` to replace **all values**.

So, it may be possible that this PR is unnecessary.  However, if we find it is still necessary, then we likely should add automated tests to prove the new behavior.

2025-02-16 15:32 UTC, minurmin commented
I tested a modified version (=partially ported to DSpace 7) of the PR https://github.com/DSpace/dspace-angular/pull/3078 and it turned out that localization can indeed be done with a PATCH add (e.g. by first clearing dc.title values and then adding localized ones with multiple add operations). The current implementation is more complex related to original one using PATCH replace extension, but nevertheless it is based on original REST contract.

2025-02-20 17:03 UTC, tdonohue requested changes
@MMilosz : Based on @minurmin 's [feedback above](https://github.com/DSpace/DSpace/pull/9610#issuecomment-2661485530), I'm going to place a temporary "block" on this PR from anyone merging it.  It **sounds like** this PR may not be necessary, and https://github.com/DSpace/dspace-angular/pull/3078 should just be updated to use `PATCH` add.

That said, I'll leave this PR open for now.  If we find it *is required*, I'll remove this block.   Once we verify it's not required at all, this PR should be closed.  Thanks!

2026-02-07 19:45 UTC, bram-atmire commented
Closing as @tdonohue determined this PR is likely unnecessary — the existing `add` PATCH operation (per RFC 6902) already supports replacing all values. @minurmin confirmed this works in practice, and the REST Contract docs were corrected separately (RestContract PR #304).

Thank you @MMilosz for raising the question — it led to improved documentation of the existing behavior.

2026-02-07 19:45 UTC, closed without merging

2026-02-07 23:58 UTC, minurmin commented
@bram-atmire Thanks for moving the process forward. However, please note that the proposed REST contract update https://github.com/DSpace/RestContract/pull/304 does not accurately reflect the current (at least the time I tested it in 2025) state of behaviour as calling PATCH add results to just one value being added and other values to be _shifted_, _not replaced_ - even if one uses path `/metadata/field.name` instead of single value `/metadata/field.name/n`. I consider this to be a bug that should addressed - whether the support for adding multiple values at once (proposed in #11018) is added or not.