Bulk edit is incompatible with controlled vocabularies
DSpace/DSpace pull request #9753
Opened 2024-08-06 09:02 UTC by ybnd

## References
Fixes #9749 

## Description
For now, this PR can serve as a demonstration of the problems described in #9749

## Instructions for Reviewers
TBD

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome).
However, reviewers may request that you complete any actions in this list if you have not done so. If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [ ] My PR is **created against the `main` branch** of code (unless it is a backport or is fixing an issue specific to an older branch).
- [ ] My PR is **small in size** (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [ ] My PR **passes Checkstyle** validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [ ] My PR **includes Javadoc** for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [ ] My PR **passes all tests and includes new/updated Unit or Integration Tests** based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [ ] My PR **includes details on how to test it**. I've provided clear instructions to reviewers on how to successfully test this fix or feature.
- [ ] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [ ] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [ ] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [ ] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

2024-12-19 15:53 UTC, kshepherd commented
Just a quick note to say I fully agree with the approach here, it fixes other unexpected behaviour when that `::` delimiter appears more than twice in a value string, too. Starting at the end and just parsing the last two segments looks good to me.

We may want to put some more explicit length testing on the parts array there, since if `parts.length` is < 3, the whole thing should probably just set the whole string as the value and return early since it must not be an authority value, and we'll avoid OOB errors.

2025-03-13 12:37 UTC, kshepherd requested changes
@ybnd I just had one note:
We may want to put some more explicit length testing on the parts array there, since if parts.length is < 3, the new method should probably just set the whole string as the value and return early since it must not be an authority value, and we'll avoid OOB errors.

Does that seem reasonable?

2025-03-31 11:51 UTC, ybnd commented
@kshepherd sorry for the delay, that's a good idea indeed.

I've implemented your suggestions, and also made sure that the authority/confidence is explicitly "unset" in both cases. Not sure if that was strictly necessary, but it seems more consistent with [this part](https://github.com/DSpace/DSpace/pull/9753/files#diff-ae5c144a690d65c268a9b2eb456d483128bd7e3f3c5d228b1d0740ae449f6006R740).

2025-04-01 08:19 UTC, kshepherd commented
@ybnd it looks like a few controlled vocab ITs are failing now (not immediately clear to me why but it seems to maybe be discarding too much, or the tests themeselves just need updating?)

2025-04-01 11:28 UTC, ybnd commented
@kshepherd 

@jensvannerum found that this was due to `authorityControlled` persisting between tests (sometimes it would work fine, sometimes not, depending on the order)
Since this is just some configuration getting read out before an import we're making it an instance property, let's see how the tests do now

2025-04-01 13:44 UTC, kshepherd approved these changes
+1 Looks great! Thanks @ybnd 
Gave this a practical test and the imported values are preserved as expected.
Merging immediately with 1 approval as this is a small change

2025-04-01 13:44 UTC, merged

2026-07-14 20:34 UTC, lgeggleston commented
It looks like there is renewed interest from the community in resolving this issue on 8.x: https://groups.google.com/g/dspace-tech/c/IyhGBF2yqTU/m/Y6lQKVCsAQAJ 

@ybnd, would you be willing to create a manual backport of this fix to 8.x possibly?

2026-07-15 13:58 UTC, ybnd commented
@lgeggleston yes certainly

This may also be a good opportunity for us to revisit https://github.com/DSpace/DSpace/issues/9896, I lost track of it