several optimizations in HAL browser login page
DSpace/DSpace pull request #9777
Opened 2024-08-27 08:50 UTC by saschaszott

## Description

This PR fixes **3 problems** in the login page of the HAL browser:

1. The **first** login attempt is always failing. Open a new **private** browser tab, go to https://demo.dspace.org/server/login.html and insert the DSpace admin credentials. You'll get a red error message:

![image](https://github.com/user-attachments/assets/dd7e4dfe-fb9a-40fc-9269-1378165ee30a)

The **second** login attempt is successful. This PR fixes this bug and the proposed bugfix works with DS 7 and 8.

2. In case, the DSpace instance supports **multiple authentication methods** the login form shows a section _Other login methods:_

![image](https://github.com/user-attachments/assets/8092aa59-f05e-4bb3-9e0c-79fbc9d3eb75)

The authentication methods are extracted from the `WWW-Authenticate` response header. In case, the DSpace instance supports only password-based and LDAP-based authentication the `WWW-Authenticate` header does **not** contain `location=`. In this case the login form has an empty _Other login methods:_ section:

![image](https://github.com/user-attachments/assets/865fb4cf-ff29-4573-a80e-bff8592a6425)

This PR fixes this bug as it shows the _Other login methods:_ section only if at least one authentication method provides a `location=` in the `WWW-Authenticate` header. This results in:

![image](https://github.com/user-attachments/assets/e8abbe0d-7b39-46ac-b623-2564fa616c78)

3. This PR removes obsolete code fragments (method parameters, CSS classes) from the CSS and JS code in `login.html`.

2024-08-29 13:55 UTC, kshepherd requested changes
Overall approach looks good, thanks @saschaszott ! I found a few issues:
1. the test on the authenticate header should use String.prototype.includes, there is no "contains"
2. Once I fixed #1, I noticed that the first time I clicked over to login from the home page, I immediately got the toastr error about a login failure, even though I hadn't actually attempted yet... we should be able to improve the logic here so that it doesn't report a failure until the user has actually POST'd credentials (for the first time) right?

2024-08-29 14:25 UTC, saschaszott commented
@kshepherd , thanks for the review: I've fixed the first point

2024-08-29 14:30 UTC, saschaszott commented
@kshepherd , regarding the second point: I cannot reproduce the behaviour you've mentioned (tested with different browsers). Are we using the same jQuery / toastr version?

2024-10-08 19:10 UTC, tdonohue approved these changes
👍 Thanks @saschaszott !  I tested this today and it fixes the issues that it claims to fix.  I could not reproduce the second issue that @kshepherd [reported above](https://github.com/DSpace/DSpace/pull/9777#pullrequestreview-2268851354), so I'm assuming it was something outdated on his end, or maybe fixed accidently by something else.

Merging immediately as the code looks good too.

2024-10-08 19:10 UTC, merged