Remove context parameter from AuthorityValueService methods
DSpace/DSpace pull request #9842
Opened 2024-09-19 14:15 UTC by kshepherd

## Description
Context is not used in any AuthorityValueService methods - it was only needed in `find()` for a log error message formatted with LogHeader.

This PR attempts to simplify the service and make it easier to use with tools that can't easily obtain an existing Context and would rather not create a new one (e.g. command line tools).

## Instructions for Reviewers
Please review code changes and give authority control some basic practical testing (e.g. ORCID sandbox author, or controlled vocabulary subject authority)

List of changes in this PR:
* Removed context from method signatures in `AuthorityValueService` and `AuthorityValueServiceImpl`
* Removed context parameter from calling code

## Checklist
- [ ] My PR is **created against the `main` branch** of code (unless it is a backport or is fixing an issue specific to an older branch).
- [ ] My PR is **small in size** (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [ ] My PR **passes Checkstyle** validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [ ] My PR **includes Javadoc** for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [ ] My PR **passes all tests and includes new/updated Unit or Integration Tests** based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).

2025-03-27 13:04 UTC, kshepherd commented
@atarix83 you requested to review this to make sure it did not introduce any breaking changes for CRIS. Were you able to get a chance to look into this?

2025-04-09 21:53 UTC, kshepherd commented
@atarix83 just following up on this again, do you see any problems?

2025-07-18 06:38 UTC, steph-ieffam requested changes

2025-07-18 06:38 UTC, steph-ieffam commented on dspace-api/src/main/java/org/dspace/authority/AuthorityValueServiceImpl.java
> +    @Autowired()
you can remove the parentheses altogether

2025-07-18 06:41 UTC, steph-ieffam commented
I ran a review and didn't find any issue which could lead to problems in DSpace CRIS or for the merger. The context actually seemed to be only used for logging purposes so it makes sense to me to drop it as a parameter of the methods.
I just found out some parentheses which could be dropped as well in the Autowired annotation

2025-07-18 11:02 UTC, kshepherd commented on dspace-api/src/main/java/org/dspace/authority/AuthorityValueServiceImpl.java
> +    @Autowired()
thanks, done

2025-07-18 11:02 UTC, kshepherd commented
thanks @steph-ieffam , i made the changes requested, rebased to latest main and force pushed

2025-07-18 12:31 UTC, steph-ieffam approved these changes
thanks @kshepherd, changes look good.

2025-07-18 13:48 UTC, tdonohue approved these changes
👍 Thanks @kshepherd !  Looks good to me too, and all tests pass.

2025-07-18 13:48 UTC, merged