ORCID Login flow for private emails
DSpace/DSpace pull request #9849
Opened 2024-09-24 14:09 UTC by vins01-4science

#### _Please note that this development has been funded by the [ORCID Global Participation Fund](https://info.orcid.org/global-participation-program/global-participation-fund/)._
---

dspace-7_x version DSpace/Dspace#9846
dspace-8_x version DSpace/DSpace#9847

## References
* Fixes #9087 
* Related to DSpace/RestContract#294
* Requires DSpace/dspace-angular# (todo)

## Description
Reference the description in DSpace/Dspace#9846

## Checklist
- [x] My PR is **created against the `main` branch** of code (unless it is a backport or is fixing an issue specific to an older branch).
- [ ] My PR is **small in size** (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR **passes Checkstyle** validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR **includes Javadoc** for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR **passes all tests and includes new/updated Unit or Integration Tests** based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] My PR **includes details on how to test it**. I've provided clear instructions to reviewers on how to successfully test this fix or feature.
- [x] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [x] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

2025-03-06 21:37 UTC, tdonohue requested changes
@vins01-4science : Thanks for this work.  I've given this a code review today (but I've been unable to test it because there are still code conflicts in the Angular PR). 

Overall, the code looks good, but there are a **lot** of missing JavaDocs, and I have some inline questions as well.  For instance, it's not clear to me how the new RegistrationData configurations work, as they appear to be used for **more than** just ORCID. It looks like they work for forgot password, normal registration, etc., but I'm not finding any explanation or documentation about this new table, classes or configurations.  I think I need to understand their purpose better because it's unclear to me as I read the code (and not clear from any of the other ORCID PRs).  It might make more sense once I can test this.

In any case, most of my requests are for JavaDocs or minor cleanup.  Once the Angular PR has its conflicts fixed, I'll also do my best to test this (though I may need some guidelines on how to test it.)

2025-03-06 21:37 UTC, tdonohue commented on dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/RegistrationRestRepository.java
> +    public RegistrationRest patch(
Please add Javadocs to describe this patch method's behavior/purpose

2025-03-06 21:37 UTC, tdonohue commented on dspace-server-webapp/src/test/java/org/dspace/app/rest/EPersonRegistrationRestControllerIT.java
> +            new RegistrationDataChanges("vincenzo.mecca@4science.com", RegistrationTypeEnum.VALIDATION_ORCID);
Just a note, you might not want your real email address in the codebase.  We usually use fake emails in tests.  This real email appears several times in this IT class.

2025-03-06 21:37 UTC, tdonohue commented on dspace-server-webapp/src/test/java/org/dspace/app/rest/EPersonRegistrationRestControllerIT.java
> +        ).andExpect(status().isCreated());
Tests should always try to clean up after themselves as much as possible (to avoid causing issues in later tests).  All the `POST` tests in this class appear to be leaving around data (i.e. they don't clean up the data they create).  It would be better to capture the ID of the created object (if possible) so that it can be deleted.  

See for example how this captures the ID of the created object: https://github.com/DSpace/DSpace/blob/main/dspace-server-webapp/src/test/java/org/dspace/app/rest/CommunityRestRepositoryIT.java#L199-L201
And then a few lines later *deletes* the created object: https://github.com/DSpace/DSpace/blob/main/dspace-server-webapp/src/test/java/org/dspace/app/rest/CommunityRestRepositoryIT.java#L212-L213

These tests should ideally do the same thing to avoid leaving around a lot of data in the test database.

2025-03-06 21:37 UTC, tdonohue commented on dspace-server-webapp/src/test/java/org/dspace/app/rest/EPersonRestRepositoryIT.java
> +        String registrationEmail = "vincenzo.mecca@4science.com";
Again, I'd recommend putting a fake email address here.

2025-03-06 21:37 UTC, tdonohue commented on dspace/config/dspace.cfg
> +# but without the prefix `PT`:
Is there a link we can provider where the "standard DURATION format" is defined?  I'm only finding [ISO 8601](https://www.digi.com/resources/documentation/digidocs/90001488-13/reference/r_iso_8601_duration_format.htm), but this doesn't seem to be that format.  This implies to me that we need to add a link here, if possible.

2025-03-06 21:37 UTC, tdonohue commented on dspace/config/dspace.cfg
> +eperson.registration-data.token.change_password.expiration = 1H
Each of these configs needs an explanation, as they are not self-explanatory. What is the difference between `orcid.expiration` and `validation_orcid.expiration`?  Please add a description to each of these configs.

2025-03-06 21:37 UTC, tdonohue commented on dspace/config/emails/orcid
> +The DSpace-CRIS Team
This should say `The ${config.get('dspace.name')} Team`, like all other email templates

2025-03-06 21:37 UTC, tdonohue commented on dspace/config/emails/validation_orcid
> +The DSpace-CRIS Team
Same here, this should say `The ${config.get('dspace.name')} Team`, like all other email templates

2025-03-06 21:37 UTC, tdonohue commented on dspace/config/dspace.cfg
> +eperson.registration-data.scheduler.enabled = true
I'm trying to understand what happens when this is disabled.  It appears, to me, like this is written to manage all registrations into DSpace (not just ORCID).  If this is disabled, will sites no longer be able to register new users?  The description is not clear to me, so I'm trying to understand if this should be enabled by default or not.

Also, I'm wondering if this should be listed **first** among all the new configurations. Will the token settings above still work if this is set to "false"?  If not, then it probably should be listed *before* the tokens.

2025-03-07 10:58 UTC, vins01-4science commented on dspace-api/src/main/java/org/dspace/eperson/AccountServiceImpl.java
> +        log.info(LogMessage.of(() -> "Sent " + rd.getRegistrationType().getLink() + " link to " + rd.getEmail()));
Renamed the method since it's specific to the registration process with the special-link

2025-03-07 12:14 UTC, vins01-4science commented on dspace-api/src/main/resources/org/dspace/storage/rdbms/sqlmigration/postgres/V7.6_2024.09.24__registration_data.sql
> +			WHERE TABLE_SCHEMA = 'public' AND TABLE_NAME = 'registrationdata' AND COLUMN_NAME = 'email'
Okay, I will remove the check on the public shema.
The name of the constraint is never defined in our previous flyway migration files, so it might differ in some versions of postgresql ( not 100% sure about that ).
I would prefer to take the `constraint_name` and then delete it, like it has been done on that line.

2025-03-07 15:49 UTC, vins01-4science commented
> @vins01-4science : You marked much of my feedback as "resolved", but you didn't make any code changes on this PR. Maybe you forgot to push your local changes up to this PR? I'll gladly rereview this once the changes appear in the PR.

Yes, I am working on it just marking things before pushing and requesting your review.
I am going to update the PR shortly.

Thank you!

2025-03-07 17:55 UTC, vins01-4science commented
Could you please review my latest changes @tdonohue ?
Thank you.

2025-03-07 18:21 UTC, tdonohue commented on dspace/config/dspace.cfg
> +eperson.registration-data.scheduler.enabled = true
@vins01-4science : Can you please add more details to the comments above this setting to describe the behavior.  Currently, the description is vague as it just says "Configuration that enables the schedulable tasks related to the registration".  It sounds like, from what you are saying, this is enabling automatic cleanup of invalid/expired tokens?  If that's correct, then we need to add that to the description (as I find the phrase "schedulable tasks" to be very vague -- it doesn't say what these tasks are actually doing, and why you might want this setting enabled or disabled.)

2025-03-07 18:31 UTC, tdonohue reviewed
@vins01-4science : Thanks for the quick updates.  I've given this a very quick re-review, and I've verified that all my code review feedback has been addressed except for one line below.  I also did make a request about describing the `eperson.registration-data.scheduler.enabled` configuration a bit better (see above).

I'll still need to obviously test this out once the frontend is ready. But the code is looking good now, thanks!

2025-03-07 18:31 UTC, tdonohue commented on dspace-api/src/main/java/org/dspace/eperson/service/AccountService.java
> +    RegistrationData renewRegistrationForEmail(
Please add details into the JavaDocs for this method.  Currently it's empty.

2025-03-12 19:19 UTC, vins01-4science commented
@tdonohue I've update the PR, let me know if I can help with something else.

Thank you.

2025-03-12 21:05 UTC, tdonohue commented on dspace-api/src/main/resources/org/dspace/storage/rdbms/sqlmigration/postgres/V7.6_2024.09.24__registration_data.sql
> +--
@vins01-4science : In my attempts to test this PR, I'm having difficulty getting this migration to automatically run in Docker because it's seen as "out of order" when compared to the other 9.0 migrations.  Since the migration doesn't run automatically, it results in Hibernate errors (because of missing columns in "registrationdata") which cause the Docker instance to error out (and stop running).

Could we consider renaming this to be `V9.0_2025.03.12__registration_data.sql`?  It also doesn't make sense to me that we'd name this migration "V7.6" because it will not be backported officially to DSpace 7.6 because this is a new feature.  The release where this feature will first be available will be 9.0.

2025-03-25 14:53 UTC, tdonohue commented
@vins01-4science : Reminder that this PR is waiting on addressing of feedback in my last review: https://github.com/DSpace/DSpace/pull/9849#pullrequestreview-2679865984

The migration should be renamed to start with `V9.0` because this feature is new in 9.0 and will not be backported.

2025-03-26 19:50 UTC, tdonohue approved these changes
👍 Thanks @vins01-4science !  I re-reviewed this today and tested it as well.  Everything seems to be working.  I can successfully see the email come from sandbox.orcid.org if it's shared.  If it's not shared, then I'm prompted to enter an email & then must click on a verification link sent to that email.  I also tested the scenario of linking my ORCID login with an existing login in DSpace.  All those appear to work well.

This is ready to merge, but it will require documentation in the 9.0 Documenation area: https://wiki.lyrasis.org/display/DSDOC9x/  Specifically, we should document the new authentication process/workflow.  We also should document all the new configurations added to `dspace.cfg`.

2025-03-26 19:53 UTC, merged

2025-04-01 22:12 UTC, tdonohue commented
@vins01-4science or @atarix83 : Would someone at 4Science be able to add documentation for this feature in our 9.0 docs? https://wiki.lyrasis.org/display/DSDOC9x   Ideally, basic documentation would exist prior to our [9.0 Testathon](https://wiki.lyrasis.org/display/DSPACE/DSpace+Release+9.0+Testathon+Page) (which starts on Monday, April 7).  But, if it cannot exist by then, it should hopefully be created shortly thereafter.

2025-04-30 14:39 UTC, tdonohue commented
@vins01-4science and @atarix83 : Friendly reminder that this feature still isn't documented for 9.0.  We need to add documentation for how the login flow for ORCID has changed in 9.0 to https://wiki.lyrasis.org/display/DSDOC9x/ORCID+Integration#ORCIDIntegration-LoginviaORCID

2025-06-09 15:08 UTC, tdonohue commented
@vins01-4science or @atarix83  : I've just realized that the new configurations in this PR are not yet documented:
```
eperson.registration-data.token.orcid.expiration = 1H
eperson.registration-data.token.validation_orcid.expiration = 1H
eperson.registration-data.token.forgot.expiration = 24H
eperson.registration-data.token.register.expiration = 24H
eperson.registration-data.token.invitation.expiration = 24H
eperson.registration-data.token.change_password.expiration = 1H

# Configuration that enables the schedulable tasks related to the registration
# The property `enabled` should be setted to true to enable it.
eperson.registration-data.scheduler.enabled = true
# Configuration for the task that deletes expired registrations.
# Its value should be compatible with the cron format.
# By default it's scheduled to be run every 15 minutes.
eperson.registration-data.scheduler.expired-registration-data.cron = 0 0/15 * * * ?
```

Could you please add documentation for these configurations to https://wiki.lyrasis.org/display/DSDOC9x/Configuration+Reference (or similar)?