Provide a setting to use a different REST url during SSR execution
DSpace/DSpace pull request #9856
Opened 2024-09-26 18:04 UTC by atarix83

## References

* Fixes https://github.com/DSpace/dspace-angular/issues/1485
* Related to https://github.com/DSpace/dspace-angular/pull/3358

## Description
This is the REST pull request needed for https://github.com/DSpace/dspace-angular/pull/3358

## Instructions for Reviewers
List of changes in this PR:
* Added a new setting `dspace.server.ssr.url` where to specify a different DSpace REST url to use during SSR by the angular application
* Changed the `getBaseObjectRestFromUri` of the `Utils.java` that is used by the authorizations endpoint to verify if the object uri is valid. The check is done considering the url set in the `dspace.server.url`. With this PR also uri which contains the `dspace.server.ssr.url` should be considered valid

**Include guidance for how to test or review your PR.** 
Please see instruction present in the Angular PR

## Checklist
- [x] My PR is **created against the `main` branch** of code (unless it is a backport or is fixing an issue specific to an older branch).
- [x] My PR is **small in size** (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR **passes Checkstyle** validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR **includes Javadoc** for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR **passes all tests and includes new/updated Unit or Integration Tests** based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] My PR **includes details on how to test it**. I've provided clear instructions to reviewers on how to successfully test this fix or feature.
- [x] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [x] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

2024-11-07 19:59 UTC, mwoodiupui commented on dspace-server-webapp/src/main/java/org/dspace/app/rest/utils/Utils.java
> +            }
What about adding `else { dspaceUrlSSRObject = dspaceUrlObject; }` and dropping all of the subsequent is-blank tests.  IOW dspaceUrlSSRObject is never null.

2024-11-15 22:03 UTC, tdonohue requested changes
@atarix83 : Thanks for this!  I gave this a code review today, and found some areas where the code could be simplified (see inline comments below).  Overall though, this looks reasonable.

(I was not able to find time to test this yet, but plan to do so next week)

2025-01-09 11:27 UTC, atarix83 commented
@tdonohue 
I've addressed your feedback, ready to be reviewed again

2025-01-09 12:13 UTC, atarix83 commented on dspace-server-webapp/src/test/java/org/dspace/app/rest/AuthorizationRestRepositoryIT.java
> +    public void findByObjectBadRequestSSRTest() throws Exception {
I've copied and pasted the name and description of the method above and forgot to fix it. Now it should be fine. I've also add two more tests

2025-01-14 18:33 UTC, tdonohue reviewed
@atarix83 : Just wanted to note that I gave this a code review today & the code looks good now.  I'm +1 to this backend PR overall, but I'll wait to formally approve it until the frontend bugs are fixed (just in case some of those bugs involve backend changes).   See my latest review of the frontend PR: https://github.com/DSpace/dspace-angular/pull/3358#pullrequestreview-2550107822

2025-01-31 21:09 UTC, tdonohue requested changes
@atarix83 : I gave the new changes a quick code review.  Overall, the changes make sense & are proven to work by the new tests.  However, I have a small suggestion below which I think we should consider.  I'm a little worried about the structure of the if/else clause.

2025-01-31 21:09 UTC, tdonohue commented on dspace-server-webapp/src/main/java/org/dspace/app/rest/converter/RootConverter.java
> +            rootRest.setDspaceServer(dspaceSSRUrl);
Overall, this new code looks good.  However, I'm slightly concerned that this `if / else` clause **defaults** to using the SSR URL (which is an internal URL).   

I *think* that likely shouldn't matter in most cases. But, if some site is using *two public URLs*, then there's a chance they will hit the `else` clause if they use the URL which is *not* in `dspace.server.url`.  That seems incorrect.

Maybe we should write this the other way around, and have the **default** be the `dspace.server.url`.  Something like:
```
if (!dspaceUrl.equals(dspaceSSRUrl) && requestUrl.startsWith(dspaceSSRUrl)) {
  rootRest.setDspaceServer(dspaceSSRUrl);
} else {
  rootRest.setDspaceServer(dspaceUrl);
}
```

I think the above code is "safer" because the fallback will be the current behavior of using the value in `dspace.server.url`

2025-02-03 13:43 UTC, atarix83 commented on dspace-server-webapp/src/main/java/org/dspace/app/rest/converter/RootConverter.java
> +            rootRest.setDspaceServer(dspaceSSRUrl);
I agreed and applied this change

2025-02-03 22:20 UTC, tdonohue approved these changes
👍 Thanks @atarix83 !  This looks good to me now.  Code all looks good, and I tested it alongside the UI PR as noted in https://github.com/DSpace/dspace-angular/pull/3358#pullrequestreview-2591220421

2025-02-05 22:20 UTC, pnbecker commented
I tested the backport to DSpace 8 of this PR in a production environment. There were two URLs to access the backend: one was accessible only from my browser, the other one from the frontend. The one accessible from my browser filtered the access based on the connecting ip address, the other one was routed via a private IP address space which my browser had no access to. The frontend was able to access the backend only via the private ip.

I was able to login, to submit a new Item, to load thumbnails and files with JavaScript switched off, and to load the sitemap. I was not able to search and browse without JavaScript, which is not a surprise after we merged the PR to limit SSR to certain paths and to exclude search and browse from ssr.

👍 I did not review the code, I just tested it.

2025-02-06 16:06 UTC, merged

2025-02-06 16:09 UTC, tdonohue commented
@atarix83 : As discussed in today's meeting, this will need to be ported manually to `dspace-7_x`.  Please let me know when you have a backport PR completed.