Introducing batching with configurable batch size for DOI operations (MAIN)
DSpace/DSpace pull request #9869
Opened 2024-10-01 13:55 UTC by bram-atmire

## References
* Fixes https://github.com/DSpace/DSpace/issues/9622
* DSpace 9/Main port of https://github.com/DSpace/DSpace/pull/9865

## Description
Instead of a single commit for all operations, the operations can now be committed in batches.

## Instructions for Reviewers
Put a couple of 1000 DOIs in one of the update statuses.
Run with default code & observe throughput/memory usage.
Compare with the batched approach

## Checklist

- [x] My PR is **created against the `main` branch** of code (unless it is a backport or is fixing an issue specific to an older branch). 
- [x] My PR is **small in size** (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [ ] My PR **passes Checkstyle** validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR **includes Javadoc** for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [ ] My PR **passes all tests and includes new/updated Unit or Integration Tests** based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] My PR **includes details on how to test it**. I've provided clear instructions to reviewers on how to successfully test this fix or feature.
- **N/A** If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- **N/A** If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- **N/A** If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

2024-10-01 16:21 UTC, tdonohue commented
@bram-atmire : This PR has some Checkstyle violations which need cleanup.

2025-01-09 16:19 UTC, mwoodiupui commented
This might collide with https://github.com/DSpace/DSpace/pull/9835, which effectively establishes a fixed batch size of 1.

2025-01-09 16:32 UTC, tdonohue commented
@mwoodiupui : Just to clarify.  Do you feel #9835 should also "solve" the performance issues mentioned in #9622?

If so, then we should perhaps compare the approaches in both, and choose which one seems better for the long term. 

I'm just unclear what you mean by "collide".  Do you mean they do the same thing in different ways?  Or are you just pointing out they may have merge conflicts?

2025-01-10 17:22 UTC, mwoodiupui commented
@tdonohue Probably collide in both ways.  They modify the same areas of the code, and they affect the memory requirements of the operation.

The underlying issue is the one we have all over DSpace in bulk operations:  doing an unlimited number of updates of unrelated objects in a single transaction.  A side effect of fixing (in #9835) the one-failure-aborts-whole-batch problem is to break down the single giant transaction into individual transactions for each DOI.  There's no reason for a single transaction, since the DOIs are unrelated.  This should address the memory pressure issue.

2025-01-10 20:27 UTC, tdonohue commented
> Now that I've looked more closely at the present patch, it seems to be taking the same approach as the other, with the added complexity of managing batches. I'm not convinced that that complexity is needed

@mwoodiupui : Yes, I agree with this, which is why I asked for clarification.  I saw the same thing, and wondered myself if your #9835 (which seems cleaner to me -- at least at a glance) would likely solve the same problem as this PR.  It's starting to sound like we need to choose *one* of these PRs to apply, and see how it works.  We can always improve things later.

I'm going to assign @kshepherd and I to review your #9835 (since we are both assigned here).  That way we can look at these together and choose the approach we prefer.

2025-01-20 15:55 UTC, vins01-4science requested changes
### Problems Found
The main issue of #9896 and #9835 is that we are trying to load the whole result set in memory just to split it into chunks / commiting them separately. We need to tune this behavior in my opinion.

### Review
All the code changes are placed inside the DOIOrganiser itself, this could be improved by moving out some unrelated code ( at least the functional interface ), since it's getting really huge.
Moreover, I suggest to change from functional approach to OOP, since the `DOIOperation` would not be self contained, and the code that has been written inside this class is doing different things ( Update, Delete and so on).
It seems to be a good use case for a `Strategy` pattern, maybe with a bean factory tha would retrieve a specific implementation at runtime.

I cannot see any test for this changes, however we don't have a real Test suite for this class.

I found out some checkstyle issues:

```shell
[INFO] --- checkstyle:3.3.1:check (default-cli) @ dspace-api ---
[INFO] There are 16 errors reported by Checkstyle 8.38 with /home/vins/dev/projects/DSpace7/dspace/dspace-api/../checkstyle.xml ruleset.
[ERROR] src/main/java/org/dspace/identifier/doi/DOIOrganiser.java:[19,1] (imports) CustomImportOrder: 'jakarta.mail.MessagingException' should be separated from previous import group by one line.
[ERROR] src/main/java/org/dspace/identifier/doi/DOIOrganiser.java:[21,1] (imports) CustomImportOrder: Extra separation in import group before 'org.apache.commons.cli.CommandLine'
[ERROR] src/main/java/org/dspace/identifier/doi/DOIOrganiser.java:[265] (sizes) LineLength: Line is longer than 120 characters (found 122).
[ERROR] src/main/java/org/dspace/identifier/doi/DOIOrganiser.java:[279] (sizes) LineLength: Line is longer than 120 characters (found 124).
[ERROR] src/main/java/org/dspace/identifier/doi/DOIOrganiser.java:[310] (sizes) LineLength: Line is longer than 120 characters (found 121).
[ERROR] src/main/java/org/dspace/identifier/doi/DOIOrganiser.java:[458] (sizes) LineLength: Line is longer than 120 characters (found 122).
[ERROR] src/main/java/org/dspace/identifier/doi/DOIOrganiser.java:[472] (sizes) LineLength: Line is longer than 120 characters (found 126).
[ERROR] src/main/java/org/dspace/identifier/doi/DOIOrganiser.java:[485] (regexp) RegexpSingleline: Line has trailing whitespace
[ERROR] src/main/java/org/dspace/identifier/doi/DOIOrganiser.java:[486] (sizes) LineLength: Line is longer than 120 characters (found 136).
[ERROR] src/main/java/org/dspace/identifier/doi/DOIOrganiser.java:[492] (sizes) LineLength: Line is longer than 120 characters (found 135).
[ERROR] src/main/java/org/dspace/identifier/doi/DOIOrganiser.java:[498] (sizes) LineLength: Line is longer than 120 characters (found 129).
[ERROR] src/main/java/org/dspace/identifier/doi/DOIOrganiser.java:[692] (sizes) LineLength: Line is longer than 120 characters (found 123).
[ERROR] src/main/java/org/dspace/identifier/doi/DOIOrganiser.java:[718] (regexp) RegexpSingleline: Line has trailing whitespace
[ERROR] src/main/java/org/dspace/identifier/doi/DOIOrganiser.java:[724] (regexp) RegexpSingleline: Line has trailing whitespace
[ERROR] src/main/java/org/dspace/identifier/doi/DOIOrganiser.java:[730] (regexp) RegexpSingleline: Line has trailing whitespace
[ERROR] src/main/java/org/dspace/identifier/doi/DOIOrganiser.java:[736] (regexp) RegexpSingleline: Line has trailing whitespace

```

### Conclusions
I would suggest to improve the code readability of these changes, and since neither this #9896 or #9835 are really addressing the _fetching into memory issue_ I would suggest to take a different approach by doing a paginated query. What do you think @tdonohue @mwoodiupui @bram-atmire ?

2025-01-20 15:55 UTC, vins01-4science commented on dspace-api/src/main/java/org/dspace/identifier/doi/DOIOrganiser.java
> +                }
We are removing from the cache only the last processed doi of each batch.
It should be applied to all `doiRow`s.

2025-01-20 15:55 UTC, vins01-4science commented on dspace-api/src/main/java/org/dspace/identifier/doi/DOIOrganiser.java
> +            provider.updateMetadataOnline(context, doi.getDSpaceObject(), DOI.SCHEME + doi.getDoi()),
It would be nice to extract `DOI.SCHEME + doi.getDoi()` with a more meaningful variable / method  since it's duplicated in other lines.

2025-01-20 15:55 UTC, vins01-4science commented on dspace-api/src/main/java/org/dspace/identifier/doi/DOIOrganiser.java
> +            "update");
Since we are linking the operation variable (i.e. `update`) to a specific method ( i.e. `updateMetadataOnline` and this pattern is valid also for the other operations it should be mapped in a better way.

2025-01-20 15:55 UTC, vins01-4science commented on dspace-api/src/main/java/org/dspace/identifier/doi/DOIOrganiser.java
> +    private void performDOIOperation(DOI doiRow, DOIOperation operation, String operationName) {
`operationName` could be set as a property of `DOIOperation`, instead of passing it as an argument to this function.
This would allow a much cleaner approach and would bound that specific `operationName` to a given `Strategy` implemented with a specialized `DOIOperation`.

2025-01-27 16:32 UTC, tdonohue commented
@bram-atmire : The original bug in #9622 should be re-tested now that #9835 has been merged.  It's possible that bug has improved the behavior somewhat.  

If this PR is still necessary, then it would require refactoring along the lines of what @vins01-4science [suggests above](https://github.com/DSpace/DSpace/pull/9869#pullrequestreview-2562445701).  Currently, it's not in a mergeable state.

2026-02-07 11:07 UTC, bram-atmire commented
Closing this PR. PR #9835 was merged over a year ago and addressed the immediate reliability concern (one failure aborting the entire batch) by committing after each individual DOI operation. The reviewers preferred that approach over the batching complexity introduced here.

Regarding the broader scalability issue in #9622: the per-DOI commit in #9835 reduces per-transaction memory pressure, which helps. However, the root cause — `DOIDAOImpl.findByStatus()` loading **all** matching DOIs into a single `List<DOI>` with no pagination (`list(context, criteriaQuery, false, DOI.class, -1, -1)`) — remains. For repositories with very large DOI queues (10K+), this could still cause memory issues.

If that needs to be addressed in the future, the right approach (as @vins01-4science suggested) would be DAO-level pagination in a new, clean PR — not a rework of this one.

2026-02-07 11:07 UTC, closed without merging