Generic External Bitstream Storage Based on Apache JClouds
DSpace/DSpace pull request #9915
Opened 2024-10-21 17:50 UTC by mdiggory

## References
_Add references/links to any related issues or PRs. These may include:_
* Fixes Fixes  https://github.com/DSpace/DSpace/issues/8115 
* Related to https://github.com/DSpace/DSpace/issues/7325 

## Description

Provides DSpace with a Bistore based on the Apache JClouds framework to support storing content in multiple cloud vendors. JCloudStore which can be configured inside of bitstore.xml. This store can be connected to any storage provider supported here https://jclouds.apache.org/ and allows saving bitstreams to the connected Cloud container. This allows for DSpace to support a multitude of storage options, for example, Microsoft Azure, Google Cloud Storage, or independent S3 providers such as MinIO.

This functionality was made possible through the support of the[ Flemish Government - Departement Omgeving](https://omgeving.vlaanderen.be/), who generously sponsored its development for the benefit of the open-source community.

## Instructions for Reviewers

To enabled setup the following in bitstore.xml with some kind of local object store configured. For the example provided:
```

<bean name="org.dspace.storage.bitstore.BitstreamStorageService" class="org.dspace.storage.bitstore.BitstreamStorageServiceImpl">
        <property name="incoming" value="${assetstore.index.primary}"/>
        <property name="stores">
            <map>
                <entry key="0" value-ref="localStore"/>
                <entry key="1" value-ref="s3Store"/>
                <entry key="2" value-ref="jcloudStore"/>
            </map>
        </property>
    </bean>
    
    <bean name="jcloudStore" class="org.dspace.storage.bitstore.JCloudBitStoreService" scope="singleton" lazy-init="true">
        <property name="enabled" value="${assetstore.s3.generic.enabled:false}"/>
        <property name="useRelativePath" value="${assetstore.s3.generic.useRelativePath:false}"/>
        <property name="container" value="${assetstore.s3.generic.container}"/>
        <property name="endpoint" value="${assetstore.s3.endpoint}"/>

        <property name="providerOrApi" value="${assetstore.s3.generic.provider}"/>
        <property name="identity" value="${assetstore.s3.generic.awsAccessKey}"/>
        <property name="credentials" value="${assetstore.s3.generic.awsSecretKey}"/>
        <property name="maxCounter" value="${assetstore.s3.maxCounter:100}"/>

        Subfolder to organize assets within the bucket, in case this bucket is shared
        Optional, default is root level of bucket
        <property name="subFolder" value="${assetstore.s3.generic.subfolder}"/>
    </bean>
```

Specific connection properties may then be set in the dspace configuration

```
Then all assetstore.s3.generic must be defined in shared.cfg 

# Enabled the assetstore [true|false]
assetstore.s3.generic.enabled=true

# The storage container/bucket of the object store that this service will use. [bucketname]
assetstore.s3.generic.container=bucket_name

# Endpoint of the storage service [http://endpoint]
assetstore.s3.endpoint=

# https://jclouds.apache.org/reference/providers/#blobstore  Which provider we are using from the list of supported ones.
assetstore.s3.provider

# Private key or username for the store
assetstore.s3.generic.awsAccessKey

# Private password for the store
assetstore.s3.generic.awsSecretKey

# How many times the store will connection will be used before reconnection
assetstore.s3.maxCounter

# Subfolder all files will be stored in inside of the container/bucket.
assetstore.s3.generic.subfolder

```
Then attempt to create new items with bitstreams, delete items with bitstreams and replace item bitstreams.

List of changes in this PR:
* Inclusion of Apache JClouds libraries via Maven depdnencies
* Assignment of compatable Google Guava, Guise and GSon versions
* Addition of new method to BitstreamStorageSertvice to support setting the incoming external store for unit tests
* JCloudBitstore implementation
* JCloudBitTStoreServiceTest based on Mock and local JClouds file storage.

## Checklist

- [x] My PR is created against the main branch of code (unless it is a backport or is fixing an issue specific to an older branch).
- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the Code Style Guide.
- [x] My PR includes Javadoc for all new (or modified) public methods and classes. It also includes Javadoc for large or complex private methods.
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the Code Testing Guide.
- [x] My PR includes details on how to test it. I've provided clear instructions to reviewers on how to successfully test this fix or feature.
- [x] If my PR includes new libraries/dependencies (in any pom.xml), I've made sure their licenses align with the DSpace BSD License based on the Licensing of Contributions documentation
- [x] If my PR modifies REST API endpoints, I've opened a separate REST Contract PR related to this change.
- [x] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've linked them together.

2024-10-31 14:44 UTC, kshepherd commented
@mdiggory what value should i set in `providerOrApi` (`assetstore.s3.generic.provider`) for a self-hosted S3 instance like MinIO? Is `aws-s3` compatible, or do I just set `s3` (as in, the API)?

2024-11-07 23:17 UTC, mdiggory commented
> @mdiggory what value should i set in `providerOrApi` (`assetstore.s3.generic.provider`) for a self-hosted S3 instance like MinIO? Is `aws-s3` compatible, or do I just set `s3` (as in, the API)?

@kshepherd the providers that are supported are available in the JClouds site/documentation https://jclouds.apache.org/reference/providers/#blobstore

Here is a sample of the settings that one might set for MinIO

property | default | Description
-- | -- | --
assetstore.s3.generic.enabled | true | Enables the JClouds configuration
assetstore.s3.generic.provider | s3 | Enables the generic s3 provider in the JCouldsBitstore
assetstore.s3.generic.subfolder | assetstore | if enabled, a subfolder will be added to the container
assetstore.s3.generic.useRelativePath | true | if enabled, will use relative path hashing for assetstore file assetstore/12/34/56/1234567890... otherwise it will be stored in the subfolder assetstore/1234567890...`
assetstore.s3.generic.container | my-assetstore-bucket | The Container (S3 Bucket) that objects should be stored within.
assetstore.s3.endpoint | http://localhost:9000 | Provide the appropriate URL to the Minio S3 Endpoint
private.s3.generic.awsAccessKey |   | Access Key for S3 Repository
private.s3.generic.awsSecretKey |   | Access Credential for S3 Repository

2025-02-20 15:13 UTC, kshepherd requested changes
Overall this is +1, just a minor config typo to fix and it needs to be rebased to main.

I tested by resolving conflicts myself on my dev machine (@mdiggory I am happy to force push this if you like, otherwise I will wait for you to rebase when you get a chance), and then testing again against a MinIO test instance with the `s3` provider.

Uploads and downloads worked well, alongside existing assetstores. The code and tests all look good to me too.

2025-02-20 15:13 UTC, kshepherd commented on dspace/config/spring/api/bitstore.xml
> +        <property name="subFolder" value="${assetstore.s3.generic.subfolder}"/>
This property name should be `subfolder`, it will cause a spring startup error otherwise

2025-03-05 16:27 UTC, pnbecker commented
@mdiggory @tdonohue  I would love to see this in DSpace 9.0. @kshepherd did a review, tested it and offered to resolve the merge conflict or can you fix this please @mdiggory?

2025-03-05 17:15 UTC, pnbecker commented
@abollini I'm curious what you think of this PR?

2025-03-07 22:44 UTC, mdiggory commented on dspace/config/spring/api/bitstore.xml
> +        <property name="subFolder" value="${assetstore.s3.generic.subfolder}"/>
I've redone the merge on the latest `main` revisions and made the adjustment to use `subfolder`

2025-03-07 23:00 UTC, tdonohue submitted a review, later dismissed
@mdiggory : I noticed a few mistakes in the POMs after you've cleaned up this PR.  I think one of your rebases may have accidentally pulled back in a bunch of dependencies we recently worked to remove.  See inline below.  (I haven't had a chance to test this or give it a thorough review...I just stumbled on these mistakes in the POM)

2025-03-13 01:48 UTC, mdiggory commented on pom.xml
> +            <dependency>
@tdonohue issue should now be resolved in pom files.

Additional changes:
- improved property naming convention
- provided additional documentation in java classes and configuration files.
- added support to disable counter that periodically reloads BlobContext (connection pool)

Additional testing completed
- verified aws-s3 configuration allows upload, download and successful cleanup of both small and large bitstreams greater that 6GB

2025-03-13 01:48 UTC, mdiggory commented on dspace-api/pom.xml
> +        <dependency>
@tdonohue issue should now be resolved in pom files.

2025-03-17 16:43 UTC, tdonohue reviewed
@mdiggory :  I gave this a code review today.  Overall, the code looks good.  I have a few questions/comments inline, but I basically approve of the code.

I'm not able to easily *test* this myself, so I'll have to rely on one of the other reviewers to give it a test.  Overall though it looks good to me, just some suggestions inline below.

2025-03-17 16:43 UTC, tdonohue commented on dspace-api/pom.xml
> +            <version>2.6.0</version>
If all these JClouds dependencies should be "synced" in terms of the version, then we may want to pull this out into a property named `jclouds.version` along all the other `version` properties in our main POM: https://github.com/DSpace/DSpace/blob/main/pom.xml#L31-L59.

This is optional, but I wanted to call it out as it might make future updates to this dependency a bit easier.

2025-03-17 16:43 UTC, tdonohue commented on dspace-api/src/test/data/dspaceFolder/config/local.cfg
> +assetstore.jcloud.container = assetstore-jclouds-container
I'm a little nervous about setting these test configs *globally*, as it can sometimes result in side effects for other tests (especially in scenarios where tests are run in a different order).  Are these even necessary? Maybe I'm overlooking it, but it seems like these may not be used in your tests.

If you do need them in tests, the ideal scenario is to set them per test by doing `configurationService.setProperty(name, value);`  That will set the property for the remainder of your tests.

For example, see how this is achieved for `S3BitStoreServiceIT`, which is similarly setting these values for S3 tests.

2025-03-17 16:43 UTC, tdonohue commented on dspace-api/src/test/data/dspaceFolder/config/spring/api/bitstore.xml
> +                <entry key="2" value-ref="jcloudStore"/>
Similar to the above, unless this `bitstore.xml` is absolutely necessary for your tests, I'd rather remove this entire file.  Global settings like this can have unexpected side effects later on if the order of tests is changed.

I'm also noticing that the existing `S3BitStoreServiceIT` manages to test the Amazon S3 storage option **without** requiring this `bitstore.xml`.  Could we do something similar for JClouds here?

(If I'm missing something and this is required by your tests, then feel free to disregard this comment)

2025-03-17 16:43 UTC, tdonohue commented on dspace/config/spring/api/bitstore.xml
> +    <bean name="jcloudStore" class="org.dspace.storage.bitstore.JCloudBitStoreService" scope="singleton" lazy-init="true">
Oh, maybe this being commented out is why you had to create a test copy of `bitstore.xml`?  Is there a reason to keep this commented out, or should we consider uncommenting it by default?  I notice the S3 version is uncommented by default.

2025-03-17 16:50 UTC, pnbecker commented
@tdonohue we tested it with two different custom S3 stores. We did not test it with AWS. We dud not test any of the other JCloud drivers. But, I expect testing it with DSpace should be good enough, testing it with different drivers is not necessary on my opinion. 
we’ll take a backported version into production this week.

2025-03-17 16:55 UTC, tdonohue commented
@pnbecker : If you and/or @kshepherd approve of this PR, then please do remember to submit your approval here in GitHub.  I was aware you did some early testing, but this PR currently has zero +1 votes.  I'm generally in approval, but had some new feedback/questions above.  So, this needs someone else to formally approve of the latest code.

2025-03-17 17:09 UTC, pnbecker commented
@tdonohue I see. I talked to @kshepherd. He will test the latest changes and then give it an official +1.

2025-03-18 12:45 UTC, kshepherd approved these changes
+1 thanks @mdiggory , I have tested again since the latest changes and everything looks good. the new config property names look better to me too.

I don't have a strong opinion on the test config / enable by default discussion.
I don't see a risk in enabling jcloud by default in bitstore.xml, so if that simplifies things for integration testing then that's great. But I don't personally see the test spring configs and "disabled by default" as a blocker.

2025-03-18 12:45 UTC, kshepherd commented on dspace-api/src/test/data/dspaceFolder/config/spring/api/bitstore.xml
> +                <entry key="2" value-ref="jcloudStore"/>
`S3BitStoreServiceIT` can test without a separate `bitstore.xml` because it's enabled by default in the core `bitstore.xml`, whereas jcloud isn't.
I could see an argument that we could be less conservative about commenting out jcloud config by default, as long as we don't touch the primary assetstore config.

2025-03-18 14:22 UTC, tdonohue commented on dspace-api/src/test/data/dspaceFolder/config/spring/api/bitstore.xml
> +                <entry key="2" value-ref="jcloudStore"/>
@kshepherd : Yes, that's essentially what I'm asking in this comment & the one *below*.  Should we consider just uncommenting the `jcloudStore` bean *by default* in `bitstore.xml`?  It seems, to me, like it shouldn't do any harm, and it'd allow us to avoid duplicating the `bitstore.xml` in this test directory.  

But, if there is a concern with enabling that `jcloudStore` bean by default, then I'm OK with leaving this test `bitstore.xml` around.  I just wanted to ask that question since it looks like we took a different approach with the `s3Store` bean (which is enabled by default in Spring files, but not actually used until you configure it).

Generally speaking, since the `assetstore.jcloud.enabled` configuration exists, it seems like it'd be nice to have the bean uncommented by default.  Otherwise, the `assetstore.jcloud.enabled` configuration doesn't really *do anything* until you first uncomment the bean.

2025-03-18 14:55 UTC, mwoodiupui commented
I find myself asking if this should be an IT at all.  A UT can instantiate BitstreamStorageService using any `stores` map it needs.  What do we need to prove here?  Is it necessary to fire up the whole application to do that?

2025-03-24 20:04 UTC, mdiggory commented
the testing verifies that the JClouds store works with the filesystem option enabled, if a different approach is required to close the pull request, please request it, otherwise the previouse requests up to this point have been resolved and the conflicts cleared.

2025-03-24 21:13 UTC, tdonohue commented
@mdiggory : I think we still need your response to the questions in the last set of reviews above before we can move this forward. 
See, specifically, my last review: https://github.com/DSpace/DSpace/pull/9915#pullrequestreview-2691164513 especially this comment https://github.com/DSpace/DSpace/pull/9915#discussion_r2001176882

I believe you can *simplify* and remove a lot of the test configuration if you enable (uncomment) the `jcloudStore` Spring bean by default.  That also would allow the `assetstore.jcloud.enabled` to act more as users may expect.  

Currently, in this PR, it appears to be a two step process to use JClouds: (1) First you have to manually uncomment the `jcloudStore` bean, and (2) then set `assetstore.jcloud.enabled = true`.   I think this code would better align with our other Storage plugins if it was a one-step process, where it can be easily enabled just by setting `assetstore.jcloud.enabled = true`.

Once that feedback is either responded to or addressed, then this PR looks good.  Thanks!

2025-03-28 15:11 UTC, tdonohue commented
@mdiggory : Friendly reminder this PR is waiting on minor updates from you (see prior message).  I'd **really** like to get this into 9.0, but we have to merge this by early next week in order to achieve that.

2025-03-29 16:08 UTC, mdiggory commented on dspace/config/spring/api/bitstore.xml
> +    <bean name="jcloudStore" class="org.dspace.storage.bitstore.JCloudBitStoreService" scope="singleton" lazy-init="true">
I've uncommended the JCloudStore configuration in bitstore.xml and removed the version from the test directory.

2025-03-29 16:13 UTC, mdiggory commented on dspace-api/src/test/data/dspaceFolder/config/local.cfg
> +assetstore.jcloud.container = assetstore-jclouds-container
As these are only used to initialize the JCloud assetstore to use the filesystem provider and place the files in the local target directory while testing, there should not be impacts due to ordering of other tests.

This configuration is used for the BitstreamJCloudBitstoreTest that ensures that the JCloudsBitstore provider generates expected results when enabled and actual content is added/removed from the storage api.

2025-03-29 16:17 UTC, mdiggory commented
> @mdiggory : Friendly reminder this PR is waiting on minor updates from you (see prior message). I'd **really** like to get this into 9.0, but we have to merge this by early next week in order to achieve that.

@tdonohue I've adjusted the configuration so that the JCloudsStore can be enabled through assetstore.cfg and reduced the need for the test bitstore.xml

2025-03-31 20:10 UTC, tdonohue approved these changes
👍 Thanks @mdiggory ! This looks good to me now.  Since this is at +2 it can be merged.

That said, I'll flag this with "needs documentation" as we need to get Documentation for this new storage option added to the DSpace 9.0 Docs at https://wiki.lyrasis.org/display/DSDOC9x/

2025-03-31 20:10 UTC, merged

2025-04-01 22:14 UTC, tdonohue commented
@mdiggory : Would someone at Atmire be able to add documentation for this feature in our 9.0 docs? https://wiki.lyrasis.org/display/DSDOC9x   Ideally, basic documentation would exist prior to our [9.0 Testathon](https://wiki.lyrasis.org/display/DSPACE/DSpace+Release+9.0+Testathon+Page) (which starts on Monday, April 7).  But, if it cannot exist by then, it should hopefully be created shortly thereafter.

2025-04-25 19:08 UTC, mdiggory commented
initital documentation regarding configuration of the provider has been added here https://wiki.lyrasis.org/display/DSDOC9x/Storage+Layer#StorageLayer-ConfiguringJCloudstoreforAssetStorage

2025-04-25 19:11 UTC, tdonohue commented
Thanks @mdiggory !