added expunge request param and enabled workflowitem delete based on it
DSpace/DSpace pull request #9950
Opened 2024-11-04 00:45 UTC by oscar-escire

## References
* Fixes DSpace/dspace-angular#3086

## Description
This PR enables a param called expunge in the corresponding delete endpoint to allow workflow item delete from workflow process.

## Instructions for Reviewers
1. Go to a collection with workflow process enabled
2. Generate a new item deposit in the collection
3. Deposit the item
4. Go to workflow administration
5. Search the new item 
6. If you press on send back button, the delete method only sends item back to workspace
7. if you press on delete button, the delete method will delete the item enterely

List of changes in this PR:
* Added expunge param to delete methods
* Enabled a new method on WorkflowitemRestRepository to delete workflow item
* Enabled abstract method on DspaceRestRepository

I skipped the PR to the REST contracts repository because the current documentation points out that if you add expunge param on delete method on workflowitem requests, the item will deleted, but it was not working, and no other endpoints will be affected with this PR

## Checklist

- [x] My PR is **created against the `main` branch** of code (unless it is a backport or is fixing an issue specific to an older branch).
- [x] My PR is **small in size** (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR **passes Checkstyle** validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR **includes Javadoc** for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR **passes all tests and includes new/updated Unit or Integration Tests** based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] My PR **includes details on how to test it**. I've provided clear instructions to reviewers on how to successfully test this fix or feature.
- [x] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [x] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

2024-11-05 17:02 UTC, pilasou commented
Hi @oscar-escire, hi @tdonohue, I tested this PR using DSpace Docker environnement and everything behave accordingly. I tested as described in the PR: 

1. I made a new submission in a collection with worflow (1-step Workflow collection, in DSpace test data) using Submitter account.
2. As admin, in Admin Workflow, I find the new submission and clic on "Send Back button".
3. As submitter, the item is back in my workspace. I resubmit.
4. As admin, in Admin Workflow, I find the new submission and clic on "Delete" button.
5. The delete Item confirmation page is displayed. I confirmed deletion: 
- Submission disapeared from the Admin workflow section.
- As submitter, the item is not listed anymore in MyDSpace (_Your submissions_ page).

2025-01-10 18:05 UTC, tdonohue requested changes
@oscar-escire: Apologies for taking so long to give this a code review.  I'm worried about the current implementation in this PR because you appear to be adding the `expunge` parameter to every endpoint.

This shouldn't be necessary, as you should be able to ONLY check for the `expunge` parameter on the workflowitem endpoint.  We do something similar already with the Item endpoint which checks for a `copyVirtualMetadata` parameter in order to determine how to perform the delete.  See the code at https://github.com/DSpace/DSpace/blob/main/dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/ItemRestRepository.java#L153-L155

This PR also needs to have Integration Tests added to prove that the "expunge" parameter is working differently than the default DELETE request (without expunge).

2025-01-14 18:55 UTC, oscar-escire commented
Hi @tdonohue don't worry about the time, thanks for the review. I'll check your comments and improve the PR, I expect to send you a new version this week.

2025-01-23 22:43 UTC, oscar-escire commented
Hello @tdonohue, I update the PR with a new version of the change, it enable "expunge" param only in the workflowitem's endpoint and also add a IT test to validate the endpoint when the param is present.

2025-01-24 16:07 UTC, tdonohue approved these changes
👍 Thanks @oscar-escire !  The code looks good now.  I tested this and verified that it works properly now.  "Delete" performs full deletion (via expunge) and "Send back" still just sends the item back to the submitter.

2025-01-24 16:08 UTC, merged